Board Games Collection: ReverseXO_Board Class Reference
ReverseXO_Board Class Reference
#include <XO_Classes.h>
Public Member Functions
ReverseXO_Board ()
bool update_board (Move< char > *move)
Update the board with a new move.
bool is_win (Player< char > *player)
Check if a player has won.
bool is_lose (Player< char > *player)
Check if a player has lost.
bool is_draw (Player< char > *player)
Check if the game ended in a draw.
bool game_is_over (Player< char > *player)
Check if the game is over.
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Attributes
char blank_symbol = '.'
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Definition at line 34 of file XO_Classes.h.
Constructor & Destructor Documentation
ReverseXO_Board()
ReverseXO_Board::ReverseXO_Board ()
Definition at line 21 of file XO_Classes.cpp.
                                 : Board(3, 3)
{
    for (auto& row : board)
        for (auto& cell : row)
            cell = blank_symbol;
}
References blank_symbol, Board< char >::Board(), and Board< char >::board.
Member Function Documentation
game_is_over()
bool ReverseXO_Board::game_is_over (Player< char > *) virtual
Check if the game is over.
Implements Board< char >.
Definition at line 135 of file XO_Classes.cpp.
{
    return is_win(player) || is_lose(player) || is_draw(player);
}
References is_draw(), is_lose(), and is_win().
is_draw()
bool ReverseXO_Board::is_draw (Player< char > *) virtual
Check if the game ended in a draw.
Implements Board< char >.
Definition at line 127 of file XO_Classes.cpp.
{
    return (n_moves == 9 && !is_lose(player) && !is_win(player));
}
References is_lose(), is_win(), and Board< char >::n_moves.
Referenced by game_is_over().
is_lose()
bool ReverseXO_Board::is_lose (Player< char > *) virtual
Check if a player has lost.
Implements Board< char >.
Definition at line 103 of file XO_Classes.cpp.
{
    const char sym = player->get_symbol();
    auto all_equal = [&](char a, char b, char c) {
        return a == b && b == c && a != blank_symbol;
        };
    for (int i = 0; i < rows; ++i) {
        if ((all_equal(board[i][0], board[i][1], board[i][2]) && board[i][0] == sym) ||
            (all_equal(board[0][i], board[1][i], board[2][i]) && board[0][i] == sym))
            return true;
    }
    if ((all_equal(board[0][0], board[1][1], board[2][2]) && board[1][1] == sym) ||
        (all_equal(board[0][2], board[1][1], board[2][0]) && board[1][1] == sym))
        return true;
    return false;
}
References blank_symbol, Board< char >::board, Player< T >::get_symbol(), and Board< char >::rows.
Referenced by game_is_over(), and is_draw().
is_win()
bool ReverseXO_Board::is_win (Player< char > *) virtual
Check if a player has won.
Implements Board< char >.
Definition at line 99 of file XO_Classes.cpp.
{
    return false;
}
Referenced by game_is_over(), and is_draw().
update_board()
bool ReverseXO_Board::update_board (Move< char > * move) virtual
Update the board with a new move.
Parameters
move The move object containing position and symbol.
Returns
true if the move is valid and applied, false otherwise.
Implements Board< char >.
Definition at line 52 of file XO_Classes.cpp.
{
    int x = move->get_x();
    int y = move->get_y();
    char symbol = move->get_symbol();
    if (!(x < 0 || x >= rows || y < 0 || y >= columns) &&
        (board[x][y] == blank_symbol || symbol == 0)) {
        if (symbol == 0) {
            n_moves--;
            board[x][y] = blank_symbol;
        }
        else {
            n_moves++;
            board[x][y] = toupper(symbol);
        }
        return true;
    }
    return false;
}
References blank_symbol, Board< char >::board, Board< char >::columns, Move< T >::get_symbol(), Move< T >::get_x(), Move< T >::get_y(), Board< char >::n_moves, and Board< char >::rows.
Member Data Documentation
blank_symbol
char ReverseXO_Board::blank_symbol = '.' private
Definition at line 36 of file XO_Classes.h.
Referenced by is_lose(), ReverseXO_Board(), and update_board().
The documentation for this class was generated from the following files:
XO/XO_Classes.h
XO/XO_Classes.cpp