Board Games Collection: SUS_UI Class Reference
SUS_UI Class Reference
#include <XO_Classes.h>
Public Member Functions
SUS_UI ()
Player< char > * create_player (string &name, char symbol, PlayerType type) override
Move< char > * get_move (Player< char > *player) override
Ask the user (or AI) to make a move.
Player< char > ** setup_players () override
Set up players for the game.
Public Member Functions inherited from UI< char >
UI (int cell_display_width=3)
Construct the UI and display a welcome message.
virtual ~UI ()
virtual void display_message (string message)
Display any message to the user.
virtual Player< char > * create_player (string &name, char symbol, PlayerType type)
Create a player object based on input name, symbol, and type.
virtual void display_board_matrix (const vector< vector< char > > &matrix) const
Display the current board matrix in formatted form.
Additional Inherited Members
Protected Member Functions inherited from UI< char >
virtual string get_player_name (string player_label)
Ask the user for the player's name.
virtual PlayerType get_player_type_choice (string player_label, const vector< string > &options)
Ask the user to choose the player type from a list.
Protected Attributes inherited from UI< char >
int cell_width
Width of each displayed board cell.
Detailed Description
Definition at line 319 of file XO_Classes.h.
Constructor & Destructor Documentation
SUS_UI()
SUS_UI::SUS_UI ()
Definition at line 1757 of file XO_Classes.cpp.
: UI<char>("Welcome to SUS Game (S-U-S Sequence)", 3) {}
References UI< char >::UI().
Member Function Documentation
create_player()
Player< char > * SUS_UI::create_player (string & name, char symbol, PlayerType type) override
Definition at line 1759 of file XO_Classes.cpp.
{
    return new Player<char>(name, symbol, type);
}
Referenced by setup_players().
get_move()
Move< char > * SUS_UI::get_move (Player< char > *) override virtual
Ask the user (or AI) to make a move.
Implements UI< char >.
Definition at line 1763 of file XO_Classes.cpp.
{
    int x, y;
    char mark = player->get_symbol();
    Board<char>* board_ptr = player->get_board_ptr();
    if (player->get_type() == PlayerType::HUMAN) {
        bool valid_input = false;
        while (!valid_input) {
            cout << "\nPlayer " << player->get_name() << " (" << mark << "), enter move (Row Col) in the range (0 - 0) to (2 - 2): ";
            if (!(cin >> x >> y)) {
                cout << " Invalid input format. Please enter two numbers for coordinates (Row Col) in the range 0-2.\n";
                cin.clear();
                cin.ignore(numeric_limits<streamsize>::max(), '\n');
                continue;
            }
            if (x < 0 || x >= board_ptr->get_rows() || y < 0 || y >= board_ptr->get_columns()) {
                cout << " Coordinate out of range. Please enter numbers between 0 and 2.\n";
                continue;
            }
            if (board_ptr->get_board_matrix()[x][y] != '.') {
                cout << " That cell is already occupied. Choose an empty cell.\n";
                continue;
            }
            valid_input = true;
        }
    }
    else {
        vector<pair<int, int>> empty_cells;
        for (int i = 0; i < board_ptr->get_rows(); ++i) {
            for (int j = 0; j < board_ptr->get_columns(); ++j) {
                if (board_ptr->get_board_matrix()[i][j] == '.') {
                    empty_cells.push_back({ i, j });
                }
            }
        }
        if (!empty_cells.empty()) {
            int rand_index = rand() % empty_cells.size();
            x = empty_cells[rand_index].first;
            y = empty_cells[rand_index].second;
        }
        else {
            return new Move<char>(-1, -1, mark);
        }
    }
    return new Move<char>(x, y, mark);
}
References Board< T >::get_board_matrix(), Player< T >::get_board_ptr(), Board< T >::get_columns(), Player< T >::get_name(), Board< T >::get_rows(), Player< T >::get_symbol(), Player< T >::get_type(), and HUMAN.
setup_players()
Player< char > ** SUS_UI::setup_players () override virtual
Set up players for the game.
Default implementation of setting up two players.
Reimplemented from UI< char >.
Definition at line 1817 of file XO_Classes.cpp.
{
    Player<char>** players = new Player<char>*[2];
    vector<string> type_options = { "Human", "Computer" };
    string name1 = get_player_name("Player S");
    PlayerType type1 = get_player_type_choice("Player S", type_options);
    players[0] = create_player(name1, 'S', type1);
    string name2 = get_player_name("Player U");
    PlayerType type2 = get_player_type_choice("Player U", type_options);
    players[1] = create_player(name2, 'U', type2);
    return players;
}
References create_player(), UI< char >::get_player_name(), and UI< char >::get_player_type_choice().
The documentation for this class was generated from the following files:
XO/XO_Classes.h
XO/XO_Classes.cpp