Board Games Collection: ReverseXO_UI Class Reference
ReverseXO_UI Class Reference
#include <XO_Classes.h>
Public Member Functions
ReverseXO_UI ()
~ReverseXO_UI ()
Player< char > * create_player (string &name, char symbol, PlayerType type)
virtual Move< char > * get_move (Player< char > *player)
Ask the user (or AI) to make a move.
Public Member Functions inherited from UI< char >
UI (int cell_display_width=3)
Construct the UI and display a welcome message.
virtual ~UI ()
virtual void display_message (string message)
Display any message to the user.
virtual Player< char > ** setup_players ()
Set up players for the game.
virtual Player< char > * create_player (string &name, char symbol, PlayerType type)
Create a player object based on input name, symbol, and type.
virtual void display_board_matrix (const vector< vector< char > > &matrix) const
Display the current board matrix in formatted form.
Additional Inherited Members
Protected Member Functions inherited from UI< char >
virtual string get_player_name (string player_label)
Ask the user for the player's name.
virtual PlayerType get_player_type_choice (string player_label, const vector< string > &options)
Ask the user to choose the player type from a list.
Protected Attributes inherited from UI< char >
int cell_width
Width of each displayed board cell.
Detailed Description
Definition at line 244 of file XO_Classes.h.
Constructor & Destructor Documentation
ReverseXO_UI()
ReverseXO_UI::ReverseXO_UI ()
Definition at line 220 of file XO_Classes.cpp.
: UI<char>("", 3) {}
References UI< char >::UI().
~ReverseXO_UI()
ReverseXO_UI::~ReverseXO_UI () inline
Definition at line 247 of file XO_Classes.h.
{};
Member Function Documentation
create_player()
Player< char > * ReverseXO_UI::create_player (string & name, char symbol, PlayerType type)
Definition at line 222 of file XO_Classes.cpp.
{
    cout << "Creating " << (type == PlayerType::HUMAN ? "human" : "computer")
        << " player: " << name << " (" << symbol << ")\n";
    return new Player<char>(name, symbol, type);
}
References HUMAN.
get_move()
Move< char > * ReverseXO_UI::get_move (Player< char > *) virtual
Ask the user (or AI) to make a move.
Implements UI< char >.
Definition at line 228 of file XO_Classes.cpp.
{
    int x, y;
    if (player->get_type() == PlayerType::HUMAN) {
        cout << "\n" << player->get_name() << "'s turn\n";
        cout << "Enter your move x and y (0 to 2): ";
        cin >> x >> y;
    }
    else if (player->get_type() == PlayerType::COMPUTER) {
        ReverseXO_Board* reverse_board = dynamic_cast<ReverseXO_Board*>(player->get_board_ptr());
        do {
            x = rand() % player->get_board_ptr()->get_rows();
            y = rand() % player->get_board_ptr()->get_columns();
        } while (reverse_board->get_board_matrix()[x][y] != '.');
        cout << "Computer plays at position (" << x << "," << y << ")\n";
    }
    return new Move<char>(x, y, player->get_symbol());
}
References COMPUTER, Board< T >::get_board_matrix(), Player< T >::get_board_ptr(), Player< T >::get_name(), Player< T >::get_symbol(), Player< T >::get_type(), and HUMAN.
The documentation for this class was generated from the following files:
XO/XO_Classes.h
XO/XO_Classes.cpp