Board Games Collection: WordXO_UI Class Reference
WordXO_UI Class Reference
#include <XO_Classes.h>
Public Member Functions
WordXO_UI ()
~WordXO_UI ()
Player< char > * create_player (string &name, char symbol, PlayerType type)
virtual Move< char > * get_move (Player< char > *player)
Ask the user (or AI) to make a move.
Public Member Functions inherited from UI< char >
UI (int cell_display_width=3)
Construct the UI and display a welcome message.
virtual ~UI ()
virtual void display_message (string message)
Display any message to the user.
virtual Player< char > ** setup_players ()
Set up players for the game.
virtual Player< char > * create_player (string &name, char symbol, PlayerType type)
Create a player object based on input name, symbol, and type.
virtual void display_board_matrix (const vector< vector< char > > &matrix) const
Display the current board matrix in formatted form.
Additional Inherited Members
Protected Member Functions inherited from UI< char >
virtual string get_player_name (string player_label)
Ask the user for the player's name.
virtual PlayerType get_player_type_choice (string player_label, const vector< string > &options)
Ask the user to choose the player type from a list.
Protected Attributes inherited from UI< char >
int cell_width
Width of each displayed board cell.
Detailed Description
Definition at line 231 of file XO_Classes.h.
Constructor & Destructor Documentation
WordXO_UI()
WordXO_UI::WordXO_UI ()
Definition at line 1240 of file XO_Classes.cpp.
: UI<char>("", 3) {}
References UI< char >::UI().
~WordXO_UI()
WordXO_UI::~WordXO_UI () inline
Definition at line 234 of file XO_Classes.h.
{};
Member Function Documentation
create_player()
Player< char > * WordXO_UI::create_player (string & name, char symbol, PlayerType type)
Definition at line 1242 of file XO_Classes.cpp.
{
    cout << "Creating " << (type == PlayerType::HUMAN ? "human" : "computer")
        << " player: " << name << " (" << symbol << ")\n";
    return new Player<char>(name, symbol, type);
}
References HUMAN.
get_move()
Move< char > * WordXO_UI::get_move (Player< char > *) virtual
Ask the user (or AI) to make a move.
Implements UI< char >.
Definition at line 1248 of file XO_Classes.cpp.
{
    int x, y;
    char letter;
    if (player->get_type() == PlayerType::HUMAN) {
        cout << "\n" << player->get_name() << "'s turn (" << player->get_symbol() << ")\n";
        cout << "Enter coordinates (row column, 0-2): ";
        cin >> x >> y;
        cout << "Enter a letter (A-Z): ";
        cin >> letter;
        letter = toupper(letter);
        if (letter < 'A' || letter > 'Z') {
            cout << "Invalid letter! Please enter A-Z.\n";
            return get_move(player);
        }
    }
    else if (player->get_type() == PlayerType::COMPUTER) {
        WordXO_Board* word_board = dynamic_cast<WordXO_Board*>(player->get_board_ptr());
        vector<pair<int, int>> empty_cells;
        for (int i = 0; i < 3; ++i) {
            for (int j = 0; j < 3; ++j) {
                if (word_board->get_board_matrix()[i][j] == '.') {
                    empty_cells.push_back({ i, j });
                }
            }
        }
        if (!empty_cells.empty()) {
            auto cell = empty_cells[rand() % empty_cells.size()];
            x = cell.first;
            y = cell.second;
            letter = 'A' + rand() % 26;
            cout << "Computer plays letter " << letter << " at position (" << x << "," << y << ")\n";
        }
        else {
            x = y = 0;
            letter = 'A';
        }
    }
    return new Move<char>(x, y, letter);
}
References COMPUTER, Board< T >::get_board_matrix(), Player< T >::get_board_ptr(), get_move(), Player< T >::get_name(), Player< T >::get_symbol(), Player< T >::get_type(), and HUMAN.
Referenced by get_move().
The documentation for this class was generated from the following files:
XO/XO_Classes.h
XO/XO_Classes.cpp