Board Games Collection: MathXO_UI Class Reference
MathXO_UI Class Reference
#include <XO_Classes.h>
Public Member Functions
MathXO_UI ()
~MathXO_UI ()
Player< int > * create_player (string &name, int symbol, PlayerType type)
virtual Move< int > * get_move (Player< int > *player)
Ask the user (or AI) to make a move.
virtual Player< int > ** setup_players ()
Set up players for the game.
Public Member Functions inherited from UI< int >
UI (int cell_display_width=3)
Construct the UI and display a welcome message.
virtual ~UI ()
virtual void display_message (string message)
Display any message to the user.
virtual Player< int > * create_player (string &name, int symbol, PlayerType type)
Create a player object based on input name, symbol, and type.
virtual void display_board_matrix (const vector< vector< int > > &matrix) const
Display the current board matrix in formatted form.
Additional Inherited Members
Protected Member Functions inherited from UI< int >
virtual string get_player_name (string player_label)
Ask the user for the player's name.
virtual PlayerType get_player_type_choice (string player_label, const vector< string > &options)
Ask the user to choose the player type from a list.
Protected Attributes inherited from UI< int >
int cell_width
Width of each displayed board cell.
Detailed Description
Definition at line 235 of file XO_Classes.h.
Constructor & Destructor Documentation
MathXO_UI()
MathXO_UI::MathXO_UI ()
Definition at line 159 of file XO_Classes.cpp.
: UI<int>("", 3) {}
References UI< int >::UI().
~MathXO_UI()
MathXO_UI::~MathXO_UI () inline
Definition at line 238 of file XO_Classes.h.
{};
Member Function Documentation
create_player()
Player< int > * MathXO_UI::create_player (string & name, int symbol, PlayerType type)
Definition at line 161 of file XO_Classes.cpp.
{
    cout << "Creating " << (type == PlayerType::HUMAN ? "human" : "computer")
        << " player: " << name << " (uses " <<
        (symbol == 1 ? "odd numbers: 1,3,5,7,9" : "even numbers: 2,4,6,8") << ")\n";
    return new Player<int>(name, symbol, type);
}
References HUMAN.
Referenced by setup_players().
get_move()
Move< int > * MathXO_UI::get_move (Player< int > *) virtual
Ask the user (or AI) to make a move.
Implements UI< int >.
Definition at line 170 of file XO_Classes.cpp.
{
    int x, y, number;
    MathXO_Board* math_board = dynamic_cast<MathXO_Board*>(player->get_board_ptr());
    if (player->get_type() == PlayerType::HUMAN) {
        vector<int> available_nums = math_board->get_available_numbers(player);
        cout << "\n" << player->get_name() << "'s turn, Available numbers: ";
        for (int num : available_nums) {
            cout << num << " ";
        }
        cout <<endl;
        cout << "Enter coordinates (row column, 0-2): ";
        cin >> x >> y;
        cout << "Enter number to place: ";
        cin >> number;
        if (!math_board->is_number_available(number, player)) {
            cout << "Number " << number << " is not available or invalid for your set!\n";
            return get_move(player);
        }
    }
    else if (player->get_type() == PlayerType::COMPUTER) {
        vector<int> available_nums = math_board->get_available_numbers(player);
        do {
            x = rand() % 3;
            y = rand() % 3;
        } while (math_board->get_board_matrix()[x][y] != 0);
        number = available_nums[rand() % available_nums.size()];
        cout << "Computer plays number " << number << " at position (" << x << "," << y << ")\n";
    }
    return new Move<int>(x, y, number);
}
References COMPUTER, MathXO_Board::get_available_numbers(), Board< T >::get_board_matrix(), Player< T >::get_board_ptr(), get_move(), Player< T >::get_name(), Player< T >::get_type(), HUMAN, and MathXO_Board::is_number_available().
Referenced by get_move().
setup_players()
Player< int > ** MathXO_UI::setup_players () virtual
Set up players for the game.
Default implementation of setting up two players.
Reimplemented from UI< int >.
Definition at line 205 of file XO_Classes.cpp.
{
    Player<int>** players = new Player<int>*[2];
    vector<string> type_options = { "Human", "Computer" };
    string name1 = get_player_name("Player 1 (Odds)");
    PlayerType type1 = get_player_type_choice("Player 1", type_options);
    players[0] = create_player(name1, 1, type1);
    string name2 = get_player_name("Player 2 (Evens)");
    PlayerType type2 = get_player_type_choice("Player 2", type_options);
    players[1] = create_player(name2, 2, type2);
    return players;
}
References create_player(), UI< int >::get_player_name(), and UI< int >::get_player_type_choice().
The documentation for this class was generated from the following files:
XO/XO_Classes.h
XO/XO_Classes.cpp