Board Games Collection: InfinityXO_Board Class Reference
InfinityXO_Board Class Reference
#include <XO_Classes.h>
Public Member Functions
InfinityXO_Board ()
bool update_board (Move< char > *move)
Update the board with a new move.
bool is_win (Player< char > *player)
Check if a player has won.
bool is_lose (Player< char > *player)
Check if a player has lost.
bool is_draw (Player< char > *player)
Check if the game ended in a draw.
bool game_is_over (Player< char > *player)
Check if the game is over.
int get_moves_since_last_removal () const
int get_total_moves () const
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Member Functions
void remove_oldest_move ()
bool has_three_in_row (char symbol)
Private Attributes
char blank_symbol = '.'
vector< pair< pair< int, int >, char > > move_history
int moves_since_last_removal = 0
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Definition at line 267 of file XO_Classes.h.
Constructor & Destructor Documentation
InfinityXO_Board()
InfinityXO_Board::InfinityXO_Board ()
Definition at line 1489 of file XO_Classes.cpp.
                                   : Board(3, 3) {
    for (auto& row : board)
        for (auto& cell : row)
            cell = blank_symbol;
    move_history.clear();
    moves_since_last_removal = 0;
}
References blank_symbol, Board< char >::Board(), Board< char >::board, move_history, and moves_since_last_removal.
Member Function Documentation
game_is_over()
bool InfinityXO_Board::game_is_over (Player< char > *) virtual
Check if the game is over.
Implements Board< char >.
Definition at line 1576 of file XO_Classes.cpp.
{
    return is_win(player);
}
References is_win().
get_moves_since_last_removal()
int InfinityXO_Board::get_moves_since_last_removal () const inline
Definition at line 284 of file XO_Classes.h.
{ return moves_since_last_removal; }
References moves_since_last_removal.
Referenced by InfinityXO_UI::get_move().
get_total_moves()
int InfinityXO_Board::get_total_moves () const inline
Definition at line 285 of file XO_Classes.h.
{ return n_moves; }
References Board< char >::n_moves.
Referenced by InfinityXO_UI::get_move().
has_three_in_row()
bool InfinityXO_Board::has_three_in_row (char symbol) private
Definition at line 1536 of file XO_Classes.cpp.
{
    for (int i = 0; i < 3; i++) {
        if (board[i][0] == symbol && board[i][1] == symbol && board[i][2] == symbol) {
            return true;
        }
    }
    for (int j = 0; j < 3; j++) {
        if (board[0][j] == symbol && board[1][j] == symbol && board[2][j] == symbol) {
            return true;
        }
    }
    if (board[0][0] == symbol && board[1][1] == symbol && board[2][2] == symbol) {
        return true;
    }
    if (board[0][2] == symbol && board[1][1] == symbol && board[2][0] == symbol) {
        return true;
    }
    return false;
}
References Board< char >::board.
Referenced by is_win().
is_draw()
bool InfinityXO_Board::is_draw (Player< char > *) virtual
Check if the game ended in a draw.
Implements Board< char >.
Definition at line 1564 of file XO_Classes.cpp.
{
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            if (board[i][j] == blank_symbol) {
                return false;
            }
        }
    }
    return !is_win(player);
}
References blank_symbol, Board< char >::board, and is_win().
is_lose()
bool InfinityXO_Board::is_lose (Player< char > *) inline virtual
Check if a player has lost.
Implements Board< char >.
Definition at line 280 of file XO_Classes.h.
{ return false; }
is_win()
bool InfinityXO_Board::is_win (Player< char > *) virtual
Check if a player has won.
Implements Board< char >.
Definition at line 1560 of file XO_Classes.cpp.
{
    return has_three_in_row(player->get_symbol());
}
References Player< T >::get_symbol(), and has_three_in_row().
Referenced by game_is_over(), and is_draw().
remove_oldest_move()
void InfinityXO_Board::remove_oldest_move () private
Definition at line 1520 of file XO_Classes.cpp.
{
    if (move_history.empty()) {
        return;
    }
    auto oldest = move_history.front();
    int x = oldest.first.first;
    int y = oldest.first.second;
    board[x][y] = blank_symbol;
    move_history.erase(move_history.begin());
    cout << "\n>>> Oldest move at (" << x << "," << y << ") has been removed!\n";
}
References blank_symbol, Board< char >::board, and move_history.
Referenced by update_board().
update_board()
bool InfinityXO_Board::update_board (Move< char > * move) virtual
Update the board with a new move.
Parameters
move The move object containing position and symbol.
Returns
true if the move is valid and applied, false otherwise.
Implements Board< char >.
Definition at line 1497 of file XO_Classes.cpp.
{
    int x = move->get_x();
    int y = move->get_y();
    char symbol = move->get_symbol();
    if (x < 0 || x >= rows || y < 0 || y >= columns || board[x][y] != blank_symbol) {
        return false;
    }
    move_history.push_back({{x, y}, symbol});
    n_moves++;
    moves_since_last_removal++;
    board[x][y] = symbol;
    if (moves_since_last_removal >= 3) {
        remove_oldest_move();
        moves_since_last_removal = 0;
    }
    return true;
}
References blank_symbol, Board< char >::board, Board< char >::columns, Move< T >::get_symbol(), Move< T >::get_x(), Move< T >::get_y(), move_history, moves_since_last_removal, Board< char >::n_moves, remove_oldest_move(), and Board< char >::rows.
Member Data Documentation
blank_symbol
char InfinityXO_Board::blank_symbol = '.' private
Definition at line 269 of file XO_Classes.h.
Referenced by InfinityXO_Board(), is_draw(), remove_oldest_move(), and update_board().
move_history
vector<pair<pair<int, int>, char> > InfinityXO_Board::move_history private
Definition at line 270 of file XO_Classes.h.
Referenced by InfinityXO_Board(), remove_oldest_move(), and update_board().
moves_since_last_removal
int InfinityXO_Board::moves_since_last_removal = 0 private
Definition at line 271 of file XO_Classes.h.
Referenced by get_moves_since_last_removal(), InfinityXO_Board(), and update_board().
The documentation for this class was generated from the following files:
XO/XO_Classes.h
XO/XO_Classes.cpp