Board Games Collection: InfinityXO_UI Class Reference
InfinityXO_UI Class Reference
#include <XO_Classes.h>
Public Member Functions
InfinityXO_UI ()
~InfinityXO_UI ()
Player< char > * create_player (string &name, char symbol, PlayerType type)
virtual Move< char > * get_move (Player< char > *player)
Ask the user (or AI) to make a move.
Public Member Functions inherited from UI< char >
UI (int cell_display_width=3)
Construct the UI and display a welcome message.
virtual ~UI ()
virtual void display_message (string message)
Display any message to the user.
virtual Player< char > ** setup_players ()
Set up players for the game.
virtual Player< char > * create_player (string &name, char symbol, PlayerType type)
Create a player object based on input name, symbol, and type.
virtual void display_board_matrix (const vector< vector< char > > &matrix) const
Display the current board matrix in formatted form.
Additional Inherited Members
Protected Member Functions inherited from UI< char >
virtual string get_player_name (string player_label)
Ask the user for the player's name.
virtual PlayerType get_player_type_choice (string player_label, const vector< string > &options)
Ask the user to choose the player type from a list.
Protected Attributes inherited from UI< char >
int cell_width
Width of each displayed board cell.
Detailed Description
Definition at line 311 of file XO_Classes.h.
Constructor & Destructor Documentation
InfinityXO_UI()
InfinityXO_UI::InfinityXO_UI ()
Definition at line 1564 of file XO_Classes.cpp.
: UI<char>("", 3) {}
References UI< char >::UI().
~InfinityXO_UI()
InfinityXO_UI::~InfinityXO_UI () inline
Definition at line 314 of file XO_Classes.h.
{};
Member Function Documentation
create_player()
Player< char > * InfinityXO_UI::create_player (string & name, char symbol, PlayerType type)
Definition at line 1566 of file XO_Classes.cpp.
{
    cout << "Creating " << (type == PlayerType::HUMAN ? "human" : "computer")
         << " player: " << name << " (" << symbol << ")\n";
    cout << "Infinity Tic-Tac-Toe Rules:\n";
    cout << "- After every 3 total moves, the oldest mark disappears\n";
    cout << "- Win by getting 3 in a row before your marks disappear!\n";
    return new Player<char>(name, symbol, type);
}
References HUMAN.
get_move()
Move< char > * InfinityXO_UI::get_move (Player< char > *) virtual
Ask the user (or AI) to make a move.
Implements UI< char >.
Definition at line 1575 of file XO_Classes.cpp.
{
    int x, y;
    InfinityXO_Board* infinity_board = dynamic_cast<InfinityXO_Board*>(player->get_board_ptr());
    if (player->get_type() == PlayerType::HUMAN) {
        cout << "\n=== " << player->get_name() << "'s turn (" << player->get_symbol() << ") ===\n";
        cout << "Moves until next removal: " << 3 - infinity_board->get_moves_since_last_removal() << "\n";
        cout << "Total moves made: " << infinity_board->get_total_moves() << "\n";
        cout << "Enter coordinates (row column, 0-2): ";
        cin >> x >> y;
        if (x < 0 || x >= 3 || y < 0 || y >= 3) {
            cout << "Invalid coordinates! Please enter values between 0-2.\n";
            return get_move(player);
        }
    }
    else if (player->get_type() == PlayerType::COMPUTER) {
        bool found = false;
        for (int i = 0; i < 3 && !found; i++) {
            for (int j = 0; j < 3 && !found; j++) {
                if (infinity_board->get_board_matrix()[i][j] == '.') {
                    x = i;
                    y = j;
                    found = true;
                }
            }
        }
        if (!found) {
            x = 0;
            y = 0;
        }
        cout << "Computer plays at position (" << x << "," << y << ")\n";
    }
    return new Move<char>(x, y, player->get_symbol());
}
References COMPUTER, Board< T >::get_board_matrix(), Player< T >::get_board_ptr(), get_move(), InfinityXO_Board::get_moves_since_last_removal(), Player< T >::get_name(), Player< T >::get_symbol(), InfinityXO_Board::get_total_moves(), Player< T >::get_type(), and HUMAN.
Referenced by get_move().
The documentation for this class was generated from the following files:
XO/XO_Classes.h
XO/XO_Classes.cpp