Board Games Collection: GameManager< T > Class Template Reference
GameManager< T > Class Template Reference
Controls the flow of a board game between two players.
#include <BoardGame_Classes.h>
Public Member Functions
GameManager (Board< T > *b, Player< T > *p[2], UI< T > *u)
Construct a game manager with board, players, and UI.
void run ()
Run the main game loop until someone wins or the game ends.
Private Attributes
Board< T > * boardPtr
Game board.
Player< T > * players [2]
Two players.
UI< T > * ui
User interface.
Detailed Description
template<typename T>
class GameManager< T >
Controls the flow of a board game between two players.
Template Parameters
T Type of symbol used on the board.
Definition at line 271 of file BoardGame_Classes.h.
Constructor & Destructor Documentation
GameManager()
template<typename T> GameManager< T >::GameManager (Board< T > * b, Player< T > * p[2], UI< T > * u) inline
Construct a game manager with board, players, and UI.
Definition at line 280 of file BoardGame_Classes.h.
        : boardPtr(b), ui(u) {
        players[0] = p[0];
        players[1] = p[1];
        players[0]->set_board_ptr(b);
        players[1]->set_board_ptr(b);
    }
References boardPtr, players, and ui.
Member Function Documentation
run()
template<typename T> void GameManager< T >::run () inline
Run the main game loop until someone wins or the game ends.
Definition at line 291 of file BoardGame_Classes.h.
               {
        ui->display_board_matrix(boardPtr->get_board_matrix());
        Player<T>* currentPlayer = players[0];
        while (true) {
            for (int i : {0, 1}) {
                currentPlayer = players[i];
                Move<T>* move = ui->get_move(currentPlayer);
                while (!boardPtr->update_board(move))
                    move = ui->get_move(currentPlayer);
                ui->display_board_matrix(boardPtr->get_board_matrix());
                if (boardPtr->is_win(currentPlayer)) {
                    ui->display_message(currentPlayer->get_name() + " wins!");
                    return;
                }
                if (boardPtr->is_lose(currentPlayer)) {
                    ui->display_message(players[1 - i]->get_name() + " wins!");
                    return;
                }
                if (boardPtr->is_draw(currentPlayer)) {
                    ui->display_message("Draw!");
                    return;
                }
            }
        }
    }
References boardPtr, Player< T >::get_name(), players, and ui.
Referenced by play_connect_four(), play_diamond_xo(), play_five_x_five(), play_four_x_four(), play_infinity_xo(), play_math_xo(), play_obstacle_xo(), play_pyramid_xo(), play_reverse_xo(), play_sus_xo(), and play_word_xo().
Member Data Documentation
boardPtr
template<typename T> Board<T>* GameManager< T >::boardPtr private
Game board.
Definition at line 272 of file BoardGame_Classes.h.
Referenced by GameManager(), and run().
players
template<typename T> Player<T>* GameManager< T >::players[2] private
Two players.
Definition at line 273 of file BoardGame_Classes.h.
Referenced by GameManager(), and run().
ui
template<typename T> UI<T>* GameManager< T >::ui private
User interface.
Definition at line 274 of file BoardGame_Classes.h.
Referenced by GameManager(), and run().
The documentation for this class was generated from the following file:
XO/BoardGame_Classes.h