Board Games Collection: PyramidXO_UI Class Reference
PyramidXO_UI Class Reference
#include <XO_Classes.h>
Public Member Functions
PyramidXO_UI ()
~PyramidXO_UI ()
Player< char > * create_player (string &name, char symbol, PlayerType type)
virtual Move< char > * get_move (Player< char > *player)
Ask the user (or AI) to make a move.
virtual void display_board_matrix (const vector< vector< char > > &matrix) const
Display the current board matrix in formatted form.
Public Member Functions inherited from UI< char >
UI (int cell_display_width=3)
Construct the UI and display a welcome message.
virtual ~UI ()
virtual void display_message (string message)
Display any message to the user.
virtual Player< char > ** setup_players ()
Set up players for the game.
virtual Player< char > * create_player (string &name, char symbol, PlayerType type)
Create a player object based on input name, symbol, and type.
Additional Inherited Members
Protected Member Functions inherited from UI< char >
virtual string get_player_name (string player_label)
Ask the user for the player's name.
virtual PlayerType get_player_type_choice (string player_label, const vector< string > &options)
Ask the user to choose the player type from a list.
Protected Attributes inherited from UI< char >
int cell_width
Width of each displayed board cell.
Detailed Description
Definition at line 258 of file XO_Classes.h.
Constructor & Destructor Documentation
PyramidXO_UI()
PyramidXO_UI::PyramidXO_UI ()
Definition at line 1418 of file XO_Classes.cpp.
: UI<char>("", 3) {}
References UI< char >::UI().
~PyramidXO_UI()
PyramidXO_UI::~PyramidXO_UI () inline
Definition at line 261 of file XO_Classes.h.
{};
Member Function Documentation
create_player()
Player< char > * PyramidXO_UI::create_player (string & name, char symbol, PlayerType type)
Definition at line 1420 of file XO_Classes.cpp.
{
    cout << "Creating " << (type == PlayerType::HUMAN ? "human" : "computer")
        << " player: " << name << " (" << symbol << ")\n";
    return new Player<char>(name, symbol, type);
}
References HUMAN.
display_board_matrix()
void PyramidXO_UI::display_board_matrix (const vector< vector< char > > & matrix) const virtual
Display the current board matrix in formatted form.
Reimplemented from UI< char >.
Definition at line 1426 of file XO_Classes.cpp.
{
    cout << "       0   1   2   3   4\n";
    cout << "      -------------------\n";
    for (int i = 0; i < 4; ++i) {
        cout << "   " << i << " |";
        for (int j = 0; j < 5; ++j) {
            cout << " " << matrix[i][j] << " |";
        }
        cout << "\n";
        if (i < 3) {
            cout << "      -------------------\n";
        }
    }
    cout << "      -------------------\n\n";
}
get_move()
Move< char > * PyramidXO_UI::get_move (Player< char > *) virtual
Ask the user (or AI) to make a move.
Implements UI< char >.
Definition at line 1444 of file XO_Classes.cpp.
{
    int x, y;
    if (player->get_type() == PlayerType::HUMAN) {
        cout << "\n" << player->get_name() << "'s turn (" << player->get_symbol() << ")\n";
        cout << "Enter coordinates (row column): ";
        cout << "\nValid rows: 0-3, Valid columns depend on row:\n";
        cout << "Row 0: column 2 only\n";
        cout << "Row 1: columns 1-3\n";
        cout << "Row 2-3: columns 0-4\n";
        cin >> x >> y;
        PyramidXO_Board* pyramid_board = dynamic_cast<PyramidXO_Board*>(player->get_board_ptr());
        if (!pyramid_board->is_valid_cell(x, y)) {
            cout << "Invalid position! That cell is not part of the pyramid.\n";
            return get_move(player);
        }
    }
    else if (player->get_type() == PlayerType::COMPUTER) {
        PyramidXO_Board* pyramid_board = dynamic_cast<PyramidXO_Board*>(player->get_board_ptr());
        vector<pair<int, int>> valid_moves;
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 5; j++) {
                if (pyramid_board->is_valid_cell(i, j) &&
                    pyramid_board->get_board_matrix()[i][j] == '.') {
                    valid_moves.push_back({ i, j });
                }
            }
        }
        if (!valid_moves.empty()) {
            auto move = valid_moves[rand() % valid_moves.size()];
            x = move.first;
            y = move.second;
            cout << "Computer plays at position (" << x << "," << y << ")\n";
        }
        else {
            x = y = 0;
        }
    }
    return new Move<char>(x, y, player->get_symbol());
}
References COMPUTER, Board< T >::get_board_matrix(), Player< T >::get_board_ptr(), get_move(), Player< T >::get_name(), Player< T >::get_symbol(), Player< T >::get_type(), HUMAN, and PyramidXO_Board::is_valid_cell().
Referenced by get_move().
The documentation for this class was generated from the following files:
XO/XO_Classes.h
XO/XO_Classes.cpp