Board Games Collection: UI< T > Class Template Reference
UI< T > Class Template Reference abstract
Base class for handling user interface and input/output.
#include <BoardGame_Classes.h>
Public Member Functions
UI (int cell_display_width=3)
Construct the UI and display a welcome message.
UI (string message, int cell_display_width)
Construct the UI and display a welcome message.
virtual ~UI ()
virtual void display_message (string message)
Display any message to the user.
virtual Move< T > * get_move (Player< T > *)=0
Ask the user (or AI) to make a move.
virtual Player< T > ** setup_players ()
Set up players for the game.
virtual Player< T > * create_player (string &name, T symbol, PlayerType type)
Create a player object based on input name, symbol, and type.
virtual void display_board_matrix (const vector< vector< T > > &matrix) const
Display the current board matrix in formatted form.
Protected Member Functions
virtual string get_player_name (string player_label)
Ask the user for the player's name.
virtual PlayerType get_player_type_choice (string player_label, const vector< string > &options)
Ask the user to choose the player type from a list.
Protected Attributes
int cell_width
Width of each displayed board cell.
Detailed Description
template<typename T>
class UI< T >
Base class for handling user interface and input/output.
Template Parameters
T The type of symbol used on the board.
Definition at line 179 of file BoardGame_Classes.h.
Constructor & Destructor Documentation
UI() [1/2]
template<typename T> UI< T >::UI (int cell_display_width = 3) inline
Construct the UI and display a welcome message.
Definition at line 209 of file BoardGame_Classes.h.
: cell_width(cell_display_width) {}
References cell_width.
UI() [2/2]
template<typename T> UI< T >::UI (string message, int cell_display_width) inline
Construct the UI and display a welcome message.
Definition at line 214 of file BoardGame_Classes.h.
        : cell_width(cell_display_width) {
        cout << message << endl;
    }
References cell_width.
~UI()
template<typename T> virtual UI< T >::~UI () inline virtual
Definition at line 219 of file BoardGame_Classes.h.
{}
Member Function Documentation
create_player()
template<typename T> Player< T > * UI< T >::create_player (string & name, T symbol, PlayerType type) virtual
Create a player object based on input name, symbol, and type.
Default implementation of creating two players.
Definition at line 346 of file BoardGame_Classes.h.
{
    // Create player based on type
    cout << "Creating " << (type == PlayerType::HUMAN ? "human" : "computer")
        << " player: " << name << " (" << symbol << ")\n";
    return new Player<T>(name, symbol, type);
}
References HUMAN.
Referenced by setup_players().
display_board_matrix()
template<typename T> virtual void UI< T >::display_board_matrix (const vector< vector< T > > & matrix) const inline virtual
Display the current board matrix in formatted form.
Reimplemented in DiamondXO_UI, FourXFour_UI, and PyramidXO_UI.
Definition at line 243 of file BoardGame_Classes.h.
{
        if (matrix.empty() || matrix[0].empty()) return;
        int rows = matrix.size();
        int cols = matrix[0].size();
        cout << "\n    ";
        for (int j = 0; j < cols; ++j)
            cout << setw(cell_width + 1) << j;
        cout << "\n   " << string((cell_width + 2) * cols, '-') << "\n";
        for (int i = 0; i < rows; ++i) {
            cout << setw(2) << i << " |";
            for (int j = 0; j < cols; ++j)
                cout << setw(cell_width) << matrix[i][j] << " |";
            cout << "\n   " << string((cell_width + 2) * cols, '-') << "\n";
        }
        cout << endl;
    }
References cell_width.
display_message()
template<typename T> virtual void UI< T >::display_message (string message) inline virtual
Display any message to the user.
Definition at line 222 of file BoardGame_Classes.h.
{ cout << message << "\n"; }
get_move()
template<typename T> virtual Move< T > * UI< T >::get_move (Player< T > *) pure virtual
Ask the user (or AI) to make a move.
Implemented in ConnectFour_UI, DiamondXO_UI, FiveXFive_UI, FourXFour_UI, InfinityXO_UI, MathXO_UI, ObstacleXO_UI, PyramidXO_UI, ReverseXO_UI, SUS_UI, and WordXO_UI.
get_player_name()
template<typename T> virtual string UI< T >::get_player_name (string player_label) inline protected virtual
Ask the user for the player's name.
Definition at line 186 of file BoardGame_Classes.h.
{
        string name;
        cout << "Enter " << player_label << " name: ";
        getline(cin >> ws, name);
        return name;
    }
Referenced by setup_players().
get_player_type_choice()
template<typename T> virtual PlayerType UI< T >::get_player_type_choice (string player_label, const vector< string > & options) inline protected virtual
Ask the user to choose the player type from a list.
Definition at line 196 of file BoardGame_Classes.h.
{
        cout << "Choose " << player_label << " type:\n";
        for (size_t i = 0; i < options.size(); ++i)
            cout << i + 1 << ". " << options[i] << "\n";
        int choice;
        cin >> choice;
        return (choice == 2) ? PlayerType::COMPUTER : PlayerType::HUMAN;
    }
References COMPUTER, and HUMAN.
Referenced by setup_players().
setup_players()
template<typename T> Player< T > ** UI< T >::setup_players () virtual
Set up players for the game.
Default implementation of setting up two players.
Reimplemented in MathXO_UI, and SUS_UI.
Definition at line 327 of file BoardGame_Classes.h.
{
    Player<T>** players = new Player<T>*[2];
    vector<string> type_options = { "Human", "Computer" };
    string nameX = get_player_name("Player X");
    PlayerType typeX = get_player_type_choice("Player X", type_options);
    players[0] = create_player(nameX, static_cast<T>('X'), typeX);
    string nameO = get_player_name("Player O");
    PlayerType typeO = get_player_type_choice("Player O", type_options);
    players[1] = create_player(nameO, static_cast<T>('O'), typeO);
    return players;
}
References create_player(), get_player_name(), and get_player_type_choice().
Referenced by play_connect_four(), play_diamond_xo(), play_five_x_five(), play_four_x_four(), play_infinity_xo(), play_math_xo(), play_obstacle_xo(), play_pyramid_xo(), play_reverse_xo(), play_sus_xo(), and play_word_xo().
Member Data Documentation
cell_width
template<typename T> int UI< T >::cell_width protected
Width of each displayed board cell.
Definition at line 181 of file BoardGame_Classes.h.
Referenced by display_board_matrix(), UI(), and UI().
The documentation for this class was generated from the following file:
XO/BoardGame_Classes.h