Board Games Collection: FourXFour_UI Class Reference
FourXFour_UI Class Reference
#include <XO_Classes.h>
Public Member Functions
FourXFour_UI ()
~FourXFour_UI ()
Player< char > * create_player (string &name, char symbol, PlayerType type)
virtual Move< char > * get_move (Player< char > *player)
Ask the user (or AI) to make a move.
virtual void display_board_matrix (const vector< vector< char > > &matrix) const
Display the current board matrix in formatted form.
Public Member Functions inherited from UI< char >
UI (int cell_display_width=3)
Construct the UI and display a welcome message.
virtual ~UI ()
virtual void display_message (string message)
Display any message to the user.
virtual Player< char > ** setup_players ()
Set up players for the game.
virtual Player< char > * create_player (string &name, char symbol, PlayerType type)
Create a player object based on input name, symbol, and type.
Additional Inherited Members
Protected Member Functions inherited from UI< char >
virtual string get_player_name (string player_label)
Ask the user for the player's name.
virtual PlayerType get_player_type_choice (string player_label, const vector< string > &options)
Ask the user to choose the player type from a list.
Protected Attributes inherited from UI< char >
int cell_width
Width of each displayed board cell.
Detailed Description
Definition at line 188 of file XO_Classes.h.
Constructor & Destructor Documentation
FourXFour_UI()
FourXFour_UI::FourXFour_UI ()
Definition at line 631 of file XO_Classes.cpp.
: UI<char>("", 3) {}
References UI< char >::UI().
~FourXFour_UI()
FourXFour_UI::~FourXFour_UI () inline
Definition at line 191 of file XO_Classes.h.
{};
Member Function Documentation
create_player()
Player< char > * FourXFour_UI::create_player (string & name, char symbol, PlayerType type)
Definition at line 633 of file XO_Classes.cpp.
{
    cout << "Creating " << (type == PlayerType::HUMAN ? "human" : "computer")
        << " player: " << name << " (" << symbol << ")\n";
    return new Player<char>(name, symbol, type);
}
References HUMAN.
display_board_matrix()
void FourXFour_UI::display_board_matrix (const vector< vector< char > > & matrix) const virtual
Display the current board matrix in formatted form.
Reimplemented from UI< char >.
Definition at line 639 of file XO_Classes.cpp.
{
    if (matrix.empty() || matrix[0].empty()) return;
    int rows = matrix.size();
    int cols = matrix[0].size();
    cout << "\n    ";
    for (int j = 0; j < cols; ++j)
        cout << setw(cell_width + 1) << j;
    cout << "\n   " << string((cell_width + 2) * cols, '-') << "\n";
    for (int i = 0; i < rows; ++i) {
        cout << setw(2) << i << " |";
        for (int j = 0; j < cols; ++j)
            cout << setw(cell_width) << matrix[i][j] << " |";
        cout << "\n   " << string((cell_width + 2) * cols, '-') << "\n";
    }
    cout << endl;
}
References UI< char >::cell_width.
get_move()
Move< char > * FourXFour_UI::get_move (Player< char > *) virtual
Ask the user (or AI) to make a move.
Implements UI< char >.
Definition at line 659 of file XO_Classes.cpp.
{
    FourXFour_Board* four_board = dynamic_cast<FourXFour_Board*>(player->get_board_ptr());
    char symbol = player->get_symbol();
    if (player->get_type() == PlayerType::HUMAN) {
        cout << "\n" << player->get_name() << "'s turn (" << symbol << ")\n";
        vector<pair<int, int>> pieces = four_board->get_player_pieces(symbol);
        cout << "Your pieces are at: ";
        for (auto& piece : pieces) {
            cout << "(" << piece.first << "," << piece.second << ") ";
        }
        cout << endl;
        int from_x, from_y, to_x, to_y;
        cout << "Enter source coordinates (row column) of piece to move: ";
        cin >> from_x >> from_y;
        cout << "Enter destination coordinates (row column): ";
        cin >> to_x >> to_y;
        if (from_x < 0 || from_x >= 4 || from_y < 0 || from_y >= 4 ||
            to_x < 0 || to_x >= 4 || to_y < 0 || to_y >= 4) {
            cout << "Invalid coordinates! Please enter values between 0-3.\n";
            return get_move(player);
        }
        int dx = abs(from_x - to_x);
        int dy = abs(from_y - to_y);
        if (!((dx == 1 && dy == 0) || (dx == 0 && dy == 1))) {
            cout << "Invalid move! You can only move to adjacent cells (horizontal or vertical).\n";
            return get_move(player);
        }
        if (four_board->get_board_matrix()[to_x][to_y] != '.') {
            cout << "Destination cell is not empty!\n";
            return get_move(player);
        }
        if (four_board->get_board_matrix()[from_x][from_y] != symbol) {
            cout << "You don't have a piece at the source location!\n";
            return get_move(player);
        }
        return new Move<char>(from_x * 10 + to_x, from_y * 10 + to_y, symbol);
    }
    else if (player->get_type() == PlayerType::COMPUTER) {
        vector<pair<int, int>> pieces = four_board->get_player_pieces(symbol);
        for (int attempts = 0; attempts < 100; attempts++) {
            int piece_idx = rand() % pieces.size();
            int from_x = pieces[piece_idx].first;
            int from_y = pieces[piece_idx].second;
            int directions[4][2] = { {0,1}, {1,0}, {0,-1}, {-1,0} };
            for (int i = 0; i < 4; i++) {
                int to_x = from_x + directions[i][0];
                int to_y = from_y + directions[i][1];
                if (to_x >= 0 && to_x < 4 && to_y >= 0 && to_y < 4 &&
                    four_board->get_board_matrix()[to_x][to_y] == '.') {
                    cout << "Computer moves piece from (" << from_x << "," << from_y
                        << ") to (" << to_x << "," << to_y << ")\n";
                    return new Move<char>(from_x * 10 + to_x, from_y * 10 + to_y, symbol);
                }
            }
        }
        return new Move<char>(0, 0, symbol);
    }
    return new Move<char>(0, 0, symbol);
}
References COMPUTER, Board< T >::get_board_matrix(), Player< T >::get_board_ptr(), get_move(), Player< T >::get_name(), FourXFour_Board::get_player_pieces(), Player< T >::get_symbol(), Player< T >::get_type(), and HUMAN.
Referenced by get_move().
The documentation for this class was generated from the following files:
XO/XO_Classes.h
XO/XO_Classes.cpp