Board Games Collection: PyramidXO_Board Class Reference
PyramidXO_Board Class Reference
#include <XO_Classes.h>
Public Member Functions
PyramidXO_Board ()
bool update_board (Move< char > *move)
Update the board with a new move.
bool is_win (Player< char > *player)
Check if a player has won.
bool is_lose (Player< char > *player)
Check if a player has lost.
bool is_draw (Player< char > *player)
Check if the game ended in a draw.
bool game_is_over (Player< char > *player)
Check if the game is over.
bool is_valid_cell (int x, int y) const
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Member Functions
void initialize_pyramid_shape ()
bool check_win (char symbol)
Private Attributes
char blank_symbol = '.'
vector< vector< bool > > valid_cells
int cols = 5
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Definition at line 238 of file XO_Classes.h.
Constructor & Destructor Documentation
PyramidXO_Board()
PyramidXO_Board::PyramidXO_Board ()
Definition at line 1294 of file XO_Classes.cpp.
                                 : Board(4, 5) {
    for (auto& row : board)
        for (auto& cell : row)
            cell = blank_symbol;
    valid_cells = vector<vector<bool>>(4, vector<bool>(5, false));
    initialize_pyramid_shape();
}
References blank_symbol, Board< char >::Board(), Board< char >::board, initialize_pyramid_shape(), and valid_cells.
Member Function Documentation
check_win()
bool PyramidXO_Board::check_win (char symbol) private
Definition at line 1355 of file XO_Classes.cpp.
{
    // Check rows
    for (int i = 0; i < 4; i++) {
        for (int j = 0; j <= 2; j++) {
            if (is_valid_cell(i, j) && is_valid_cell(i, j + 1) && is_valid_cell(i, j + 2) &&
                board[i][j] == symbol && board[i][j + 1] == symbol && board[i][j + 2] == symbol) {
                return true;
            }
        }
    }
    // Check columns
    for (int j = 0; j < 5; j++) {
        for (int i = 0; i <= 1; i++) {
            if (is_valid_cell(i, j) && is_valid_cell(i + 1, j) && is_valid_cell(i + 2, j) &&
                board[i][j] == symbol && board[i + 1][j] == symbol && board[i + 2][j] == symbol) {
                return true;
            }
        }
    }
    // Check diagonals (top-left to bottom-right)
    for (int i = 0; i <= 1; i++) {
        for (int j = 0; j <= 2; j++) {
            if (is_valid_cell(i, j) && is_valid_cell(i + 1, j + 1) && is_valid_cell(i + 2, j + 2) &&
                board[i][j] == symbol && board[i + 1][j + 1] == symbol && board[i + 2][j + 2] == symbol) {
                return true;
            }
        }
    }
    // Check diagonals (top-right to bottom-left)
    for (int i = 0; i <= 1; i++) {
        for (int j = 2; j < 5; j++) {
            if (is_valid_cell(i, j) && is_valid_cell(i + 1, j - 1) && is_valid_cell(i + 2, j - 2) &&
                board[i][j] == symbol && board[i + 1][j - 1] == symbol && board[i + 2][j - 2] == symbol) {
                return true;
            }
        }
    }
    return false;
}
References Board< char >::board, and is_valid_cell().
Referenced by is_win().
game_is_over()
bool PyramidXO_Board::game_is_over (Player< char > *) virtual
Check if the game is over.
Implements Board< char >.
Definition at line 1414 of file XO_Classes.cpp.
{
    return is_win(player) || is_draw(player);
}
References is_draw(), and is_win().
initialize_pyramid_shape()
void PyramidXO_Board::initialize_pyramid_shape () private
Definition at line 1303 of file XO_Classes.cpp.
{
    // Row 0 (top) - 1 cell
    valid_cells[0][2] = true;
    // Row 1 - 3 cells
    valid_cells[1][1] = true;
    valid_cells[1][2] = true;
    valid_cells[1][3] = true;
    // Row 2 - 3 cells (continuing the pyramid)
    valid_cells[2][0] = true;
    valid_cells[2][1] = true;
    valid_cells[2][2] = true;
    valid_cells[2][3] = true;
    valid_cells[2][4] = true;
    // Row 3 (bottom) - 5 cells
    valid_cells[3][0] = true;
    valid_cells[3][1] = true;
    valid_cells[3][2] = true;
    valid_cells[3][3] = true;
    valid_cells[3][4] = true;
    // Mark invalid cells with space
    for (int i = 0; i < 4; i++) {
        for (int j = 0; j < 5; j++) {
            if (!valid_cells[i][j]) {
                board[i][j] = ' ';
            }
        }
    }
}
References Board< char >::board, and valid_cells.
Referenced by PyramidXO_Board().
is_draw()
bool PyramidXO_Board::is_draw (Player< char > *) virtual
Check if the game ended in a draw.
Implements Board< char >.
Definition at line 1403 of file XO_Classes.cpp.
{
    for (int i = 0; i < 4; i++) {
        for (int j = 0; j < 5; j++) {
            if (valid_cells[i][j] && board[i][j] == blank_symbol) {
                return false;
            }
        }
    }
    return !is_win(player);
}
References blank_symbol, Board< char >::board, is_win(), and valid_cells.
Referenced by game_is_over().
is_lose()
bool PyramidXO_Board::is_lose (Player< char > *) inline virtual
Check if a player has lost.
Implements Board< char >.
Definition at line 251 of file XO_Classes.h.
{ return false; }
is_valid_cell()
bool PyramidXO_Board::is_valid_cell (int x, int y) const
Definition at line 1336 of file XO_Classes.cpp.
{
    if (x < 0 || x >= rows || y < 0 || y >= cols) return false;
    return valid_cells[x][y];
}
References cols, Board< char >::rows, and valid_cells.
Referenced by check_win(), PyramidXO_UI::get_move(), and update_board().
is_win()
bool PyramidXO_Board::is_win (Player< char > *) virtual
Check if a player has won.
Implements Board< char >.
Definition at line 1399 of file XO_Classes.cpp.
{
    return check_win(player->get_symbol());
}
References check_win(), and Player< T >::get_symbol().
Referenced by game_is_over(), and is_draw().
update_board()
bool PyramidXO_Board::update_board (Move< char > * move) virtual
Update the board with a new move.
Parameters
move The move object containing position and symbol.
Returns
true if the move is valid and applied, false otherwise.
Implements Board< char >.
Definition at line 1341 of file XO_Classes.cpp.
{
    int x = move->get_x();
    int y = move->get_y();
    char symbol = move->get_symbol();
    if (!is_valid_cell(x, y) || board[x][y] != blank_symbol) {
        return false;
    }
    n_moves++;
    board[x][y] = toupper(symbol);
    return true;
}
References blank_symbol, Board< char >::board, Move< T >::get_symbol(), Move< T >::get_x(), Move< T >::get_y(), is_valid_cell(), and Board< char >::n_moves.
Member Data Documentation
blank_symbol
char PyramidXO_Board::blank_symbol = '.' private
Definition at line 240 of file XO_Classes.h.
Referenced by is_draw(), PyramidXO_Board(), and update_board().
cols
int PyramidXO_Board::cols = 5 private
Definition at line 242 of file XO_Classes.h.
Referenced by is_valid_cell().
valid_cells
vector<vector<bool> > PyramidXO_Board::valid_cells private
Definition at line 241 of file XO_Classes.h.
Referenced by initialize_pyramid_shape(), is_draw(), is_valid_cell(), and PyramidXO_Board().
The documentation for this class was generated from the following files:
XO/XO_Classes.h
XO/XO_Classes.cpp