Board Games Collection: MathXO_Board Class Reference
MathXO_Board Class Reference
#include <XO_Classes.h>
Public Member Functions
MathXO_Board ()
bool update_board (Move< int > *move)
Update the board with a new move.
bool is_win (Player< int > *player)
Check if a player has won.
bool is_lose (Player< int > *player)
Check if a player has lost.
bool is_draw (Player< int > *player)
Check if the game ended in a draw.
bool game_is_over (Player< int > *player)
Check if the game is over.
bool is_number_available (int number, Player< int > *player)
vector< int > get_available_numbers (Player< int > *player)
Public Member Functions inherited from Board< int >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< int > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
int get_cell (int x, int y)
Return content of cell x, y in current board.
Private Attributes
vector< int > available_odds
vector< int > available_evens
int blank_symbol = 0
Additional Inherited Members
Protected Attributes inherited from Board< int >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< int > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Definition at line 16 of file XO_Classes.h.
Constructor & Destructor Documentation
MathXO_Board()
MathXO_Board::MathXO_Board ()
Definition at line 13 of file XO_Classes.cpp.
                           : Board(3, 3){
    for (auto& row : board)
        for (auto& cell : row)
            cell = blank_symbol;
    available_odds = { 1, 3, 5, 7, 9 };
    available_evens = { 2, 4, 6, 8 };
}
References available_evens, available_odds, blank_symbol, Board< int >::Board(), and Board< int >::board.
Member Function Documentation
game_is_over()
bool MathXO_Board::game_is_over (Player< int > *) virtual
Check if the game is over.
Implements Board< int >.
Definition at line 131 of file XO_Classes.cpp.
{
    return is_win(player) || is_draw(player);
}
References is_draw(), and is_win().
get_available_numbers()
vector< int > MathXO_Board::get_available_numbers (Player< int > * player)
Definition at line 149 of file XO_Classes.cpp.
{
    if (player->get_symbol() == 1) {
        return available_odds;
    }
    else {
        return available_evens;
    }
}
References available_evens, available_odds, and Player< T >::get_symbol().
Referenced by MathXO_UI::get_move().
is_draw()
bool MathXO_Board::is_draw (Player< int > *) virtual
Check if the game ended in a draw.
Implements Board< int >.
Definition at line 123 of file XO_Classes.cpp.
{
    return (n_moves == 9 && !is_win(player));
}
References is_win(), and Board< int >::n_moves.
Referenced by game_is_over().
is_lose()
bool MathXO_Board::is_lose (Player< int > *) inline virtual
Check if a player has lost.
Implements Board< int >.
Definition at line 26 of file XO_Classes.h.
{ return false; }
is_number_available()
bool MathXO_Board::is_number_available (int number, Player< int > * player)
Definition at line 139 of file XO_Classes.cpp.
{
    if (player->get_symbol() == 1) {
        return find(available_odds.begin(), available_odds.end(), number) != available_odds.end();
    }
    else {
        return find(available_evens.begin(), available_evens.end(), number) != available_evens.end();
    }
}
References available_evens, available_odds, and Player< T >::get_symbol().
Referenced by MathXO_UI::get_move().
is_win()
bool MathXO_Board::is_win (Player< int > *) virtual
Check if a player has won.
Implements Board< int >.
Definition at line 72 of file XO_Classes.cpp.
{
    int sum = 15;
    for (int i = 0; i < 3; ++i) {
        int rows = board[i][0] + board[i][1] + board[i][2];
        if (rows == sum && board[i][0] != blank_symbol &&
            board[i][1] != blank_symbol && board[i][2] != blank_symbol) {
            return true;
        }
    }
    for (int j = 0; j < 3; ++j) {
        int cols = board[0][j] + board[1][j] + board[2][j];
        if (cols == sum && board[0][j] != blank_symbol &&
            board[1][j] != blank_symbol && board[2][j] != blank_symbol) {
            return true;
        }
    }
    int diag1 = board[0][0] + board[1][1] + board[2][2];
    int diag2 = board[0][2] + board[1][1] + board[2][0];
    if ((diag1 == sum && board[0][0] != blank_symbol && board[1][1] != blank_symbol && board[2][2] != blank_symbol)
        || (diag2 == sum && board[0][2] != blank_symbol && board[1][1] != blank_symbol && board[2][0] != blank_symbol))
    {
        return true;
    }
    return false;
}
References blank_symbol, Board< int >::board, and Board< int >::rows.
Referenced by game_is_over(), and is_draw().
update_board()
bool MathXO_Board::update_board (Move< int > * move) virtual
Update the board with a new move.
Parameters
move The move object containing position and symbol.
Returns
true if the move is valid and applied, false otherwise.
Implements Board< int >.
Definition at line 28 of file XO_Classes.cpp.
{
    int x = move->get_x();
    int y = move->get_y();
    int num = move->get_symbol();
    if (x < 0 || x >= rows || y < 0 || y >= columns || board[x][y] != blank_symbol) {
        return false;
    }
    n_moves++;
    board[x][y] = num;
    if (num % 2 == 1) {
        auto i = find(available_odds.begin(), available_odds.end(), num);
        if (i != available_odds.end()) {
            available_odds.erase(i);
        }
    }
    else {
        auto i = find(available_evens.begin(), available_evens.end(), num);
        if (i != available_evens.end()) {
            available_evens.erase(i);
        }
    }
    return true;
}
References available_evens, available_odds, blank_symbol, Board< int >::board, Board< int >::columns, Move< T >::get_symbol(), Move< T >::get_x(), Move< T >::get_y(), Board< int >::n_moves, and Board< int >::rows.
Member Data Documentation
available_evens
vector<int> MathXO_Board::available_evens private
Definition at line 19 of file XO_Classes.h.
Referenced by get_available_numbers(), is_number_available(), MathXO_Board(), and update_board().
available_odds
vector<int> MathXO_Board::available_odds private
Definition at line 18 of file XO_Classes.h.
Referenced by get_available_numbers(), is_number_available(), MathXO_Board(), and update_board().
blank_symbol
int MathXO_Board::blank_symbol = 0 private
Definition at line 20 of file XO_Classes.h.
Referenced by is_win(), MathXO_Board(), and update_board().
The documentation for this class was generated from the following files:
XO/XO_Classes.h
XO/XO_Classes.cpp