Board Games Collection: SUS_Board Class Reference
SUS_Board Class Reference
#include <XO_Classes.h>
Public Member Functions
SUS_Board ()
bool update_board (Move< char > *move) override
Update the board with a new move.
bool is_win (Player< char > *player) override
Check if a player has won.
bool is_lose (Player< char > *player) override
Check if a player has lost.
bool is_draw (Player< char > *player) override
Check if the game ended in a draw.
bool game_is_over (Player< char > *player) override
Check if the game is over.
int get_player_score (int player_index) const
string get_final_result_message (Player< char > **players)
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Member Functions
int calculate_new_sus_score (int last_x, int last_y) const
Private Attributes
char blank_symbol = '.'
int player1_score = 0
int player2_score = 0
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Definition at line 214 of file XO_Classes.h.
Constructor & Destructor Documentation
SUS_Board()
SUS_Board::SUS_Board ()
Definition at line 1619 of file XO_Classes.cpp.
                     : Board(3, 3) {
    for (auto& row : board)
        for (auto& cell : row)
            cell = blank_symbol;
    player1_score = 0;
    player2_score = 0;
}
References blank_symbol, Board< char >::Board(), Board< char >::board, player1_score, and player2_score.
Member Function Documentation
calculate_new_sus_score()
int SUS_Board::calculate_new_sus_score (int last_x, int last_y) const private
Definition at line 1627 of file XO_Classes.cpp.
{
    int new_score = 0;
    char current_mark = board[last_x][last_y];
    vector<pair<int, int>> directions = { {1, 0}, {0, 1}, {1, 1}, {1, -1} };
    for (const auto& dir : directions) {
        int dx = dir.first;
        int dy = dir.second;
        if (current_mark == 'S') {
            int x1_next = last_x + dx;
            int y1_next = last_y + dy;
            int x2_next = last_x + 2 * dx;
            int y2_next = last_y + 2 * dy;
            if (is_on_board_safe(x1_next, y1_next, rows, columns) &&
                is_on_board_safe(x2_next, y2_next, rows, columns) &&
                board[x1_next][y1_next] == 'U' &&
                board[x2_next][y2_next] == 'S') {
                new_score++;
            }
        }
        if (current_mark == 'U') {
            int x_prev = last_x - dx;
            int y_prev = last_y - dy;
            int x_next = last_x + dx;
            int y_next = last_y + dy;
            if (is_on_board_safe(x_prev, y_prev, rows, columns) &&
                is_on_board_safe(x_next, y_next, rows, columns) &&
                board[x_prev][y_prev] == 'S' &&
                board[x_next][y_next] == 'S') {
                new_score++;
            }
        }
        if (current_mark == 'S') {
            int x1_prev = last_x - dx;
            int y1_prev = last_y - dy;
            int x2_prev = last_x - 2 * dx;
            int y2_prev = last_y - 2 * dy;
            if (is_on_board_safe(x1_prev, y1_prev, rows, columns) &&
                is_on_board_safe(x2_prev, y2_prev, rows, columns) &&
                board[x2_prev][y2_prev] == 'S' &&
                board[x1_prev][y1_prev] == 'U') {
                new_score++;
            }
        }
    }
    return new_score;
}
References Board< char >::board, Board< char >::columns, is_on_board_safe(), and Board< char >::rows.
Referenced by update_board().
game_is_over()
bool SUS_Board::game_is_over (Player< char > *) override virtual
Check if the game is over.
Implements Board< char >.
Definition at line 1733 of file XO_Classes.cpp.
{
    return (n_moves == 9);
}
References Board< char >::n_moves.
Referenced by play_sus_xo().
get_final_result_message()
string SUS_Board::get_final_result_message (Player< char > ** players)
Definition at line 1737 of file XO_Classes.cpp.
{
    string result;
    int score1 = get_player_score(0);
    int score2 = get_player_score(1);
    if (score1 > score2) {
        result = players[0]->get_name() + " wins with " + to_string(score1) + " point(s)!\n";
    }
    else if (score2 > score1) {
        result = players[1]->get_name() + " wins with " + to_string(score2) + " point(s)!\n";
    }
    else {
        result = " It's a draw! Both players scored " + to_string(score1) + " point(s).\n";
    }
    return result;
}
References Player< T >::get_name(), and get_player_score().
Referenced by play_sus_xo().
get_player_score()
int SUS_Board::get_player_score (int player_index) const
Definition at line 1682 of file XO_Classes.cpp.
{
    if (player_index == 0) return player1_score;
    if (player_index == 1) return player2_score;
    return 0;
}
References player1_score, and player2_score.
Referenced by get_final_result_message(), and is_win().
is_draw()
bool SUS_Board::is_draw (Player< char > *) override virtual
Check if the game ended in a draw.
Implements Board< char >.
Definition at line 1726 of file XO_Classes.cpp.
{
    if (n_moves == 9) {
        return (player1_score == player2_score);
    }
    return false;
}
References Board< char >::n_moves, player1_score, and player2_score.
is_lose()
bool SUS_Board::is_lose (Player< char > *) inline override virtual
Check if a player has lost.
Implements Board< char >.
Definition at line 226 of file XO_Classes.h.
{ return false; };
is_win()
bool SUS_Board::is_win (Player< char > *) override virtual
Check if a player has won.
Implements Board< char >.
Definition at line 1714 of file XO_Classes.cpp.
{
    if (n_moves == 9) {
        int player_index = (player->get_symbol() == 'S') ? 0 : 1;
        int current_score = get_player_score(player_index);
        int opponent_score = get_player_score(1 - player_index);
        return (current_score > opponent_score);
    }
    return false;
}
References get_player_score(), Player< T >::get_symbol(), and Board< char >::n_moves.
update_board()
bool SUS_Board::update_board (Move< char > * move) override virtual
Update the board with a new move.
Parameters
move The move object containing position and symbol.
Returns
true if the move is valid and applied, false otherwise.
Implements Board< char >.
Definition at line 1689 of file XO_Classes.cpp.
{
    int x = move->get_x();
    int y = move->get_y();
    char mark = toupper(move->get_symbol());
    if (!(x < 0 || x >= rows || y < 0 || y >= columns) &&
        (board[x][y] == blank_symbol) && (mark == 'S' || mark == 'U')) {
        n_moves++;
        board[x][y] = mark;
        int new_points = calculate_new_sus_score(x, y);
        if (mark == 'S') {
            player1_score += new_points;
        }
        else {
            player2_score += new_points;
        }
        return true;
    }
    return false;
}
References blank_symbol, Board< char >::board, calculate_new_sus_score(), Board< char >::columns, Move< T >::get_symbol(), Move< T >::get_x(), Move< T >::get_y(), Board< char >::n_moves, player1_score, player2_score, and Board< char >::rows.
Member Data Documentation
blank_symbol
char SUS_Board::blank_symbol = '.' private
Definition at line 216 of file XO_Classes.h.
Referenced by SUS_Board(), and update_board().
player1_score
int SUS_Board::player1_score = 0 private
Definition at line 217 of file XO_Classes.h.
Referenced by get_player_score(), is_draw(), SUS_Board(), and update_board().
player2_score
int SUS_Board::player2_score = 0 private
Definition at line 218 of file XO_Classes.h.
Referenced by get_player_score(), is_draw(), SUS_Board(), and update_board().
The documentation for this class was generated from the following files:
XO/XO_Classes.h
XO/XO_Classes.cpp