Board Games Collection: DiamondXO_Board Class Reference
DiamondXO_Board Class Reference
#include <XO_Classes.h>
Public Member Functions
DiamondXO_Board ()
bool update_board (Move< char > *move)
Update the board with a new move.
bool is_win (Player< char > *player)
Check if a player has won.
bool is_lose (Player< char > *player)
Check if a player has lost.
bool is_draw (Player< char > *player)
Check if the game ended in a draw.
bool game_is_over (Player< char > *player)
Check if the game is over.
bool is_valid_cell (int x, int y) const
int get_diamond_size () const
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Member Functions
bool has_three_horizontal (char symbol)
bool has_three_vertical (char symbol)
bool has_three_diagonal1 (char symbol)
bool has_three_diagonal2 (char symbol)
bool has_four_horizontal (char symbol)
bool has_four_vertical (char symbol)
bool has_four_diagonal1 (char symbol)
bool has_four_diagonal2 (char symbol)
void initialize_diamond_shape ()
Private Attributes
char blank_symbol = '.'
vector< vector< bool > > valid_cells
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Definition at line 126 of file XO_Classes.h.
Constructor & Destructor Documentation
DiamondXO_Board()
DiamondXO_Board::DiamondXO_Board ()
Definition at line 886 of file XO_Classes.cpp.
                                 : Board(7, 7) {
    for (auto& row : board)
        for (auto& cell : row)
            cell = blank_symbol;
    valid_cells = vector<vector<bool>>(7, vector<bool>(7, false));
    initialize_diamond_shape();
}
References blank_symbol, Board< char >::Board(), Board< char >::board, initialize_diamond_shape(), and valid_cells.
Member Function Documentation
game_is_over()
bool DiamondXO_Board::game_is_over (Player< char > *) virtual
Check if the game is over.
Implements Board< char >.
Definition at line 1074 of file XO_Classes.cpp.
{
    return is_win(player) || is_draw(player);
}
References is_draw(), and is_win().
get_diamond_size()
int DiamondXO_Board::get_diamond_size () const inline
Definition at line 152 of file XO_Classes.h.
{ return 7; }
has_four_diagonal1()
bool DiamondXO_Board::has_four_diagonal1 (char symbol) private
Definition at line 1020 of file XO_Classes.cpp.
{
    for (int i = 0; i <= 3; i++) {
        for (int j = 0; j <= 3; j++) {
            if (is_valid_cell(i, j) && is_valid_cell(i+1, j+1) && is_valid_cell(i+2, j+2) && is_valid_cell(i+3, j+3) &&
                board[i][j] == symbol && board[i+1][j+1] == symbol &&
                board[i+2][j+2] == symbol && board[i+3][j+3] == symbol) {
                return true;
            }
        }
    }
    return false;
}
References Board< char >::board, and is_valid_cell().
Referenced by is_win().
has_four_diagonal2()
bool DiamondXO_Board::has_four_diagonal2 (char symbol) private
Definition at line 1032 of file XO_Classes.cpp.
{
    for (int i = 0; i <= 3; i++) {
        for (int j = 3; j < 7; j++) {
            if (is_valid_cell(i, j) && is_valid_cell(i+1, j-1) && is_valid_cell(i+2, j-2) && is_valid_cell(i+3, j-3) &&
                board[i][j] == symbol && board[i+1][j-1] == symbol &&
                board[i+2][j-2] == symbol && board[i+3][j-3] == symbol) {
                return true;
            }
        }
    }
    return false;
}
References Board< char >::board, and is_valid_cell().
Referenced by is_win().
has_four_horizontal()
bool DiamondXO_Board::has_four_horizontal (char symbol) private
Definition at line 996 of file XO_Classes.cpp.
{
    for (int i = 0; i < 7; i++) {
        for (int j = 0; j <= 3; j++) {
            if (is_valid_cell(i, j) && is_valid_cell(i, j+1) && is_valid_cell(i, j+2) && is_valid_cell(i, j+3) &&
                board[i][j] == symbol && board[i][j+1] == symbol &&
                board[i][j+2] == symbol && board[i][j+3] == symbol) {
                return true;
            }
        }
    }
    return false;
}
References Board< char >::board, and is_valid_cell().
Referenced by is_win().
has_four_vertical()
bool DiamondXO_Board::has_four_vertical (char symbol) private
Definition at line 1008 of file XO_Classes.cpp.
{
    for (int j = 0; j < 7; j++) {
        for (int i = 0; i <= 3; i++) {
            if (is_valid_cell(i, j) && is_valid_cell(i+1, j) && is_valid_cell(i+2, j) && is_valid_cell(i+3, j) &&
                board[i][j] == symbol && board[i+1][j] == symbol &&
                board[i+2][j] == symbol && board[i+3][j] == symbol) {
                return true;
            }
        }
    }
    return false;
}
References Board< char >::board, and is_valid_cell().
Referenced by is_win().
has_three_diagonal1()
bool DiamondXO_Board::has_three_diagonal1 (char symbol) private
Definition at line 973 of file XO_Classes.cpp.
{
    for (int i = 0; i <= 4; i++) {
        for (int j = 0; j <= 4; j++) {
            if (is_valid_cell(i, j) && is_valid_cell(i+1, j+1) && is_valid_cell(i+2, j+2) &&
                board[i][j] == symbol && board[i+1][j+1] == symbol && board[i+2][j+2] == symbol) {
                return true;
            }
        }
    }
    return false;
}
References Board< char >::board, and is_valid_cell().
Referenced by is_win().
has_three_diagonal2()
bool DiamondXO_Board::has_three_diagonal2 (char symbol) private
Definition at line 984 of file XO_Classes.cpp.
{
    for (int i = 0; i <= 4; i++) {
        for (int j = 2; j < 7; j++) {
            if (is_valid_cell(i, j) && is_valid_cell(i+1, j-1) && is_valid_cell(i+2, j-2) &&
                board[i][j] == symbol && board[i+1][j-1] == symbol && board[i+2][j-2] == symbol) {
                return true;
            }
        }
    }
    return false;
}
References Board< char >::board, and is_valid_cell().
Referenced by is_win().
has_three_horizontal()
bool DiamondXO_Board::has_three_horizontal (char symbol) private
Definition at line 951 of file XO_Classes.cpp.
{
    for (int i = 0; i < 7; i++) {
        for (int j = 0; j <= 4; j++) {
            if (is_valid_cell(i, j) && is_valid_cell(i, j+1) && is_valid_cell(i, j+2) &&
                board[i][j] == symbol && board[i][j+1] == symbol && board[i][j+2] == symbol) {
                return true;
            }
        }
    }
    return false;
}
References Board< char >::board, and is_valid_cell().
Referenced by is_win().
has_three_vertical()
bool DiamondXO_Board::has_three_vertical (char symbol) private
Definition at line 962 of file XO_Classes.cpp.
{
    for (int j = 0; j < 7; j++) {
        for (int i = 0; i <= 4; i++) {
            if (is_valid_cell(i, j) && is_valid_cell(i+1, j) && is_valid_cell(i+2, j) &&
                board[i][j] == symbol && board[i+1][j] == symbol && board[i+2][j] == symbol) {
                return true;
            }
        }
    }
    return false;
}
References Board< char >::board, and is_valid_cell().
Referenced by is_win().
initialize_diamond_shape()
void DiamondXO_Board::initialize_diamond_shape () private
Definition at line 895 of file XO_Classes.cpp.
{
    valid_cells[0][3] = true;
    valid_cells[1][2] = true;
    valid_cells[1][3] = true;
    valid_cells[1][4] = true;
    valid_cells[2][1] = true;
    valid_cells[2][2] = true;
    valid_cells[2][3] = true;
    valid_cells[2][4] = true;
    valid_cells[2][5] = true;
    for (int j = 0; j < 7; j++) {
        valid_cells[3][j] = true;
    }
    valid_cells[4][1] = true;
    valid_cells[4][2] = true;
    valid_cells[4][3] = true;
    valid_cells[4][4] = true;
    valid_cells[4][5] = true;
    valid_cells[5][2] = true;
    valid_cells[5][3] = true;
    valid_cells[5][4] = true;
    valid_cells[6][3] = true;
    for (int i = 0; i < 7; i++) {
        for (int j = 0; j < 7; j++) {
            if (!valid_cells[i][j]) {
                board[i][j] = ' ';
            }
        }
    }
}
References Board< char >::board, and valid_cells.
Referenced by DiamondXO_Board().
is_draw()
bool DiamondXO_Board::is_draw (Player< char > *) virtual
Check if the game ended in a draw.
Implements Board< char >.
Definition at line 1063 of file XO_Classes.cpp.
{
    for (int i = 0; i < 7; i++) {
        for (int j = 0; j < 7; j++) {
            if (valid_cells[i][j] && board[i][j] == blank_symbol) {
                return false;
            }
        }
    }
    return !is_win(player);
}
References blank_symbol, Board< char >::board, is_win(), and valid_cells.
Referenced by game_is_over().
is_lose()
bool DiamondXO_Board::is_lose (Player< char > *) inline virtual
Check if a player has lost.
Implements Board< char >.
Definition at line 147 of file XO_Classes.h.
{ return false; }
is_valid_cell()
bool DiamondXO_Board::is_valid_cell (int x, int y) const
Definition at line 932 of file XO_Classes.cpp.
{
    if (x < 0 || x >= 7 || y < 0 || y >= 7) return false;
    return valid_cells[x][y];
}
References valid_cells.
Referenced by DiamondXO_UI::get_move(), has_four_diagonal1(), has_four_diagonal2(), has_four_horizontal(), has_four_vertical(), has_three_diagonal1(), has_three_diagonal2(), has_three_horizontal(), has_three_vertical(), and update_board().
is_win()
bool DiamondXO_Board::is_win (Player< char > *) virtual
Check if a player has won.
Implements Board< char >.
Definition at line 1045 of file XO_Classes.cpp.
{
    char symbol = player->get_symbol();
    if (has_three_horizontal(symbol) && has_four_vertical(symbol)) return true;
    if (has_three_horizontal(symbol) && has_four_diagonal1(symbol)) return true;
    if (has_three_horizontal(symbol) && has_four_diagonal2(symbol)) return true;
    if (has_three_vertical(symbol) && has_four_horizontal(symbol)) return true;
    if (has_three_vertical(symbol) && has_four_diagonal1(symbol)) return true;
    if (has_three_vertical(symbol) && has_four_diagonal2(symbol)) return true;
    if (has_three_diagonal1(symbol) && has_four_horizontal(symbol)) return true;
    if (has_three_diagonal1(symbol) && has_four_vertical(symbol)) return true;
    if (has_three_diagonal1(symbol) && has_four_diagonal2(symbol)) return true;
    if (has_three_diagonal2(symbol) && has_four_horizontal(symbol)) return true;
    if (has_three_diagonal2(symbol) && has_four_diagonal1(symbol)) return true;
    return false;
}
References Player< T >::get_symbol(), has_four_diagonal1(), has_four_diagonal2(), has_four_horizontal(), has_four_vertical(), has_three_diagonal1(), has_three_diagonal2(), has_three_horizontal(), and has_three_vertical().
Referenced by game_is_over(), and is_draw().
update_board()
bool DiamondXO_Board::update_board (Move< char > * move) virtual
Update the board with a new move.
Parameters
move The move object containing position and symbol.
Returns
true if the move is valid and applied, false otherwise.
Implements Board< char >.
Definition at line 937 of file XO_Classes.cpp.
{
    int x = move->get_x();
    int y = move->get_y();
    char symbol = move->get_symbol();
    if (!is_valid_cell(x, y) || board[x][y] != blank_symbol) {
        return false;
    }
    n_moves++;
    board[x][y] = toupper(symbol);
    return true;
}
References blank_symbol, Board< char >::board, Move< T >::get_symbol(), Move< T >::get_x(), Move< T >::get_y(), is_valid_cell(), and Board< char >::n_moves.
Member Data Documentation
blank_symbol
char DiamondXO_Board::blank_symbol = '.' private
Definition at line 128 of file XO_Classes.h.
Referenced by DiamondXO_Board(), is_draw(), and update_board().
valid_cells
vector<vector<bool> > DiamondXO_Board::valid_cells private
Definition at line 129 of file XO_Classes.h.
Referenced by DiamondXO_Board(), initialize_diamond_shape(), is_draw(), and is_valid_cell().
The documentation for this class was generated from the following files:
XO/XO_Classes.h
XO/XO_Classes.cpp