Board Games Collection: FiveXFive_Board Class Reference
FiveXFive_Board Class Reference
#include <XO_Classes.h>
Public Member Functions
FiveXFive_Board ()
bool update_board (Move< char > *move)
Update the board with a new move.
bool is_win (Player< char > *player)
Check if a player has won.
bool is_lose (Player< char > *player)
Check if a player has lost.
bool is_draw (Player< char > *player)
Check if the game ended in a draw.
bool game_is_over (Player< char > *player)
Check if the game is over.
int get_player_score (char symbol)
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Member Functions
int count_three_in_row (char symbol)
void calculate_final_scores ()
Private Attributes
char blank_symbol = '.'
int final_scoreX = 0
int final_scoreO = 0
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Definition at line 66 of file XO_Classes.h.
Constructor & Destructor Documentation
FiveXFive_Board()
FiveXFive_Board::FiveXFive_Board ()
Definition at line 374 of file XO_Classes.cpp.
                                 : Board(5, 5) {
    for (auto& row : board)
        for (auto& cell : row)
            cell = blank_symbol;
}
References blank_symbol, Board< char >::Board(), and Board< char >::board.
Member Function Documentation
calculate_final_scores()
void FiveXFive_Board::calculate_final_scores () private
Definition at line 424 of file XO_Classes.cpp.
{
    if (final_scoreX == 0) {
        final_scoreX = count_three_in_row('X');
        final_scoreO = count_three_in_row('O');
    }
}
References count_three_in_row(), final_scoreO, and final_scoreX.
Referenced by get_player_score(), is_draw(), and is_win().
count_three_in_row()
int FiveXFive_Board::count_three_in_row (char symbol) private
Definition at line 394 of file XO_Classes.cpp.
{
    int count = 0;
    for (int i = 0; i < rows; i++) {
        for (int j = 0; j < columns; j++) {
            if (j <= columns - 3) {
                if (board[i][j] == symbol && board[i][j + 1] == symbol && board[i][j + 2] == symbol)
                    count++;
            }
            if (i <= rows - 3) {
                if (board[i][j] == symbol && board[i + 1][j] == symbol && board[i + 2][j] == symbol)
                    count++;
            }
            if (i <= rows - 3 && j <= columns - 3) {
                if (board[i][j] == symbol && board[i + 1][j + 1] == symbol && board[i + 2][j + 2] == symbol)
                    count++;
            }
            if (i <= rows - 3 && j >= 2) {
                if (board[i][j] == symbol && board[i + 1][j - 1] == symbol && board[i + 2][j - 2] == symbol)
                    count++;
            }
        }
    }
    return count;
}
References Board< char >::board, Board< char >::columns, and Board< char >::rows.
Referenced by calculate_final_scores().
game_is_over()
bool FiveXFive_Board::game_is_over (Player< char > *) virtual
Check if the game is over.
Implements Board< char >.
Definition at line 451 of file XO_Classes.cpp.
{
    return (n_moves == 24);
}
References Board< char >::n_moves.
get_player_score()
int FiveXFive_Board::get_player_score (char symbol)
Definition at line 455 of file XO_Classes.cpp.
{
    calculate_final_scores();
    return (symbol == 'X') ? final_scoreX : final_scoreO;
}
References calculate_final_scores(), final_scoreO, and final_scoreX.
Referenced by play_five_x_five().
is_draw()
bool FiveXFive_Board::is_draw (Player< char > *) virtual
Check if the game ended in a draw.
Implements Board< char >.
Definition at line 444 of file XO_Classes.cpp.
{
    if (n_moves < 24) return false;
    calculate_final_scores();
    return final_scoreX == final_scoreO;
}
References calculate_final_scores(), final_scoreO, final_scoreX, and Board< char >::n_moves.
is_lose()
bool FiveXFive_Board::is_lose (Player< char > *) inline virtual
Check if a player has lost.
Implements Board< char >.
Definition at line 80 of file XO_Classes.h.
{ return false; }
is_win()
bool FiveXFive_Board::is_win (Player< char > *) virtual
Check if a player has won.
Implements Board< char >.
Definition at line 431 of file XO_Classes.cpp.
{
    if (n_moves < 24) return false;
    calculate_final_scores();
    if (player->get_symbol() == 'X') {
        return final_scoreX > final_scoreO;
    }
    else {
        return final_scoreO > final_scoreX;
    }
}
References calculate_final_scores(), final_scoreO, final_scoreX, Player< T >::get_symbol(), and Board< char >::n_moves.
update_board()
bool FiveXFive_Board::update_board (Move< char > * move) virtual
Update the board with a new move.
Parameters
move The move object containing position and symbol.
Returns
true if the move is valid and applied, false otherwise.
Implements Board< char >.
Definition at line 380 of file XO_Classes.cpp.
{
    int x = move->get_x();
    int y = move->get_y();
    char symbol = move->get_symbol();
    if (x < 0 || x >= rows || y < 0 || y >= columns || board[x][y] != blank_symbol) {
        return false;
    }
    n_moves++;
    board[x][y] = toupper(symbol);
    return true;
}
References blank_symbol, Board< char >::board, Board< char >::columns, Move< T >::get_symbol(), Move< T >::get_x(), Move< T >::get_y(), Board< char >::n_moves, and Board< char >::rows.
Member Data Documentation
blank_symbol
char FiveXFive_Board::blank_symbol = '.' private
Definition at line 68 of file XO_Classes.h.
Referenced by FiveXFive_Board(), and update_board().
final_scoreO
int FiveXFive_Board::final_scoreO = 0 private
Definition at line 70 of file XO_Classes.h.
Referenced by calculate_final_scores(), get_player_score(), is_draw(), and is_win().
final_scoreX
int FiveXFive_Board::final_scoreX = 0 private
Definition at line 69 of file XO_Classes.h.
Referenced by calculate_final_scores(), get_player_score(), is_draw(), and is_win().
The documentation for this class was generated from the following files:
XO/XO_Classes.h
XO/XO_Classes.cpp