Board Games Collection: ObstacleXO_Board Class Reference
ObstacleXO_Board Class Reference
#include <XO_Classes.h>
Public Member Functions
ObstacleXO_Board ()
bool update_board (Move< char > *move)
Update the board with a new move.
bool is_win (Player< char > *player)
Check if a player has won.
bool is_lose (Player< char > *player)
Check if a player has lost.
bool is_draw (Player< char > *player)
Check if the game ended in a draw.
bool game_is_over (Player< char > *player)
Check if the game is over.
int get_round_count () const
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Member Functions
void add_random_obstacles ()
bool has_four_in_row (char symbol)
Private Attributes
char blank_symbol = '.'
char obstacle_symbol = '#'
int round_count = 0
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Definition at line 46 of file XO_Classes.h.
Constructor & Destructor Documentation
ObstacleXO_Board()
ObstacleXO_Board::ObstacleXO_Board ()
Definition at line 249 of file XO_Classes.cpp.
                                   : Board(6, 6) {
    for (auto& row : board)
        for (auto& cell : row)
            cell = blank_symbol;
}
References blank_symbol, Board< char >::Board(), and Board< char >::board.
Member Function Documentation
add_random_obstacles()
void ObstacleXO_Board::add_random_obstacles () private
Definition at line 274 of file XO_Classes.cpp.
{
    int obstacles_added = 0;
    int max_attempts = 20;
    while (obstacles_added < 2 && max_attempts-- > 0) {
        int x = rand() % rows;
        int y = rand() % columns;
        if (board[x][y] == blank_symbol) {
            board[x][y] = obstacle_symbol;
            obstacles_added++;
        }
    }
}
References blank_symbol, Board< char >::board, Board< char >::columns, obstacle_symbol, and Board< char >::rows.
Referenced by update_board().
game_is_over()
bool ObstacleXO_Board::game_is_over (Player< char > *) virtual
Check if the game is over.
Implements Board< char >.
Definition at line 342 of file XO_Classes.cpp.
{
    return is_win(player) || is_draw(player);
}
References is_draw(), and is_win().
get_round_count()
int ObstacleXO_Board::get_round_count () const inline
Definition at line 63 of file XO_Classes.h.
{ return round_count; }
References round_count.
has_four_in_row()
bool ObstacleXO_Board::has_four_in_row (char symbol) private
Definition at line 293 of file XO_Classes.cpp.
{
    for (int i = 0; i < rows; ++i) {
        for (int j = 0; j <= columns - 4; ++j) {
            if (board[i][j] == symbol && board[i][j + 1] == symbol &&
                board[i][j + 2] == symbol && board[i][j + 3] == symbol) {
                return true;
            }
        }
    }
    for (int j = 0; j < columns; ++j) {
        for (int i = 0; i <= rows - 4; ++i) {
            if (board[i][j] == symbol && board[i + 1][j] == symbol &&
                board[i + 2][j] == symbol && board[i + 3][j] == symbol) {
                return true;
            }
        }
    }
    for (int i = 0; i <= rows - 4; ++i) {
        for (int j = 0; j <= columns - 4; ++j) {
            if (board[i][j] == symbol && board[i + 1][j + 1] == symbol &&
                board[i + 2][j + 2] == symbol && board[i + 3][j + 3] == symbol) {
                return true;
            }
        }
    }
    for (int i = 0; i <= rows - 4; ++i) {
        for (int j = 3; j < columns; ++j) {
            if (board[i][j] == symbol && board[i + 1][j - 1] == symbol &&
                board[i + 2][j - 2] == symbol && board[i + 3][j - 3] == symbol) {
                return true;
            }
        }
    }
    return false;
}
References Board< char >::board, Board< char >::columns, and Board< char >::rows.
Referenced by is_win().
is_draw()
bool ObstacleXO_Board::is_draw (Player< char > *) virtual
Check if the game ended in a draw.
Implements Board< char >.
Definition at line 330 of file XO_Classes.cpp.
{
    int empty_cells = 0;
    for (int i = 0; i < rows; ++i) {
        for (int j = 0; j < columns; ++j) {
            if (board[i][j] == blank_symbol) {
                empty_cells++;
            }
        }
    }
    return (empty_cells == 0 && !is_win(player));
}
References blank_symbol, Board< char >::board, Board< char >::columns, is_win(), and Board< char >::rows.
Referenced by game_is_over().
is_lose()
bool ObstacleXO_Board::is_lose (Player< char > *) inline virtual
Check if a player has lost.
Implements Board< char >.
Definition at line 59 of file XO_Classes.h.
{ return false; }
is_win()
bool ObstacleXO_Board::is_win (Player< char > *) virtual
Check if a player has won.
Implements Board< char >.
Definition at line 288 of file XO_Classes.cpp.
{
    char symbol = player->get_symbol();
    return has_four_in_row(symbol);
}
References Player< T >::get_symbol(), and has_four_in_row().
Referenced by game_is_over(), and is_draw().
update_board()
bool ObstacleXO_Board::update_board (Move< char > * move) virtual
Update the board with a new move.
Parameters
move The move object containing position and symbol.
Returns
true if the move is valid and applied, false otherwise.
Implements Board< char >.
Definition at line 255 of file XO_Classes.cpp.
{
    int x = move->get_x();
    int y = move->get_y();
    char mark = move->get_symbol();
    if (x < 0 || x >= rows || y < 0 || y >= columns ||
        board[x][y] != blank_symbol) {
        return false;
    }
    n_moves++;
    board[x][y] = toupper(mark);
    if (n_moves % 2 == 0) {
        round_count++;
        add_random_obstacles();
    }
    return true;
}
References add_random_obstacles(), blank_symbol, Board< char >::board, Board< char >::columns, Move< T >::get_symbol(), Move< T >::get_x(), Move< T >::get_y(), Board< char >::n_moves, round_count, and Board< char >::rows.
Member Data Documentation
blank_symbol
char ObstacleXO_Board::blank_symbol = '.' private
Definition at line 48 of file XO_Classes.h.
Referenced by add_random_obstacles(), is_draw(), ObstacleXO_Board(), and update_board().
obstacle_symbol
char ObstacleXO_Board::obstacle_symbol = '#' private
Definition at line 49 of file XO_Classes.h.
Referenced by add_random_obstacles().
round_count
int ObstacleXO_Board::round_count = 0 private
Definition at line 50 of file XO_Classes.h.
Referenced by get_round_count(), and update_board().
The documentation for this class was generated from the following files:
XO/XO_Classes.h
XO/XO_Classes.cpp