Board Games Collection: ConnectFour_UI Class Reference
ConnectFour_UI Class Reference
#include <XO_Classes.h>
Public Member Functions
ConnectFour_UI ()
~ConnectFour_UI ()
Player< char > * create_player (string &name, char symbol, PlayerType type)
virtual Move< char > * get_move (Player< char > *player)
Ask the user (or AI) to make a move.
Public Member Functions inherited from UI< char >
UI (int cell_display_width=3)
Construct the UI and display a welcome message.
virtual ~UI ()
virtual void display_message (string message)
Display any message to the user.
virtual Player< char > ** setup_players ()
Set up players for the game.
virtual Player< char > * create_player (string &name, char symbol, PlayerType type)
Create a player object based on input name, symbol, and type.
virtual void display_board_matrix (const vector< vector< char > > &matrix) const
Display the current board matrix in formatted form.
Additional Inherited Members
Protected Member Functions inherited from UI< char >
virtual string get_player_name (string player_label)
Ask the user for the player's name.
virtual PlayerType get_player_type_choice (string player_label, const vector< string > &options)
Ask the user to choose the player type from a list.
Protected Attributes inherited from UI< char >
int cell_width
Width of each displayed board cell.
Detailed Description
Definition at line 277 of file XO_Classes.h.
Constructor & Destructor Documentation
ConnectFour_UI()
ConnectFour_UI::ConnectFour_UI ()
Definition at line 832 of file XO_Classes.cpp.
:UI<char>("", 3){}
References UI< char >::UI().
~ConnectFour_UI()
ConnectFour_UI::~ConnectFour_UI () inline
Definition at line 280 of file XO_Classes.h.
{};
Member Function Documentation
create_player()
Player< char > * ConnectFour_UI::create_player (string & name, char symbol, PlayerType type)
Definition at line 834 of file XO_Classes.cpp.
{
    cout << "Creating " << (type == PlayerType::HUMAN ? "human" : "computer")
        << " player: " << name << " (" << symbol << ")\n";
    return new Player<char>(name, symbol, type);
}
References HUMAN.
get_move()
Move< char > * ConnectFour_UI::get_move (Player< char > *) virtual
Ask the user (or AI) to make a move.
Implements UI< char >.
Definition at line 840 of file XO_Classes.cpp.
{
    int col;
    ConnectFour_Board* connect4_board = dynamic_cast<ConnectFour_Board*>(player->get_board_ptr());
    if (player->get_type() == PlayerType::HUMAN) {
        cout << "\n" << player->get_name() << "'s turn (" << player->get_symbol() << ")\n";
        cout << "Available columns: ";
        for (int c = 0; c < 7; ++c) {
            if (!connect4_board->is_column_full(c)) {
                cout << c << " ";
            }
        }
        cout << endl;
        cout << "Enter column number (0-6): ";
        cin >> col;
        if (col < 0 || col >= 7 || connect4_board->is_column_full(col)) {
            cout << "Invalid column! Please choose an available column.\n";
            return get_move(player);
        }
        int row = connect4_board->get_lowest_empty_row(col);
        cout << "Placing piece at column " << col << ", row " << row << endl;
    }
    else if (player->get_type() == PlayerType::COMPUTER) {
        vector<int> available_columns;
        for (int c = 0; c < 7; ++c) {
            if (!connect4_board->is_column_full(c)) {
                available_columns.push_back(c);
            }
        }
        if (available_columns.empty()) {
            col = 0;
        }
        else {
            col = available_columns[rand() % available_columns.size()];
        }
        int row = connect4_board->get_lowest_empty_row(col);
        cout << "Computer plays at column " << col << endl;
    }
    return new Move<char>(0, col, player->get_symbol());
}
References COMPUTER, Player< T >::get_board_ptr(), ConnectFour_Board::get_lowest_empty_row(), get_move(), Player< T >::get_name(), Player< T >::get_symbol(), Player< T >::get_type(), HUMAN, and ConnectFour_Board::is_column_full().
Referenced by get_move().
The documentation for this class was generated from the following files:
XO/XO_Classes.h
XO/XO_Classes.cpp