Board Games Collection: FourXFour_Board Class Reference
FourXFour_Board Class Reference
#include <XO_Classes.h>
Public Member Functions
FourXFour_Board ()
bool update_board (Move< char > *move)
Update the board with a new move.
bool is_win (Player< char > *player)
Check if a player has won.
bool is_lose (Player< char > *player)
Check if a player has lost.
bool is_draw (Player< char > *player)
Check if the game ended in a draw.
bool game_is_over (Player< char > *player)
Check if the game is over.
vector< pair< int, int > > get_player_pieces (char symbol)
bool has_three_in_row (char symbol)
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Member Functions
bool isValidMove (int from_x, int from_y, int to_x, int to_y, char symbol)
bool isAdjacent (int from_x, int from_y, int to_x, int to_y)
void initializeStartingPositions ()
Private Attributes
char blank_symbol = '.'
vector< pair< int, int > > playerX_pieces
vector< pair< int, int > > playerO_pieces
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Definition at line 87 of file XO_Classes.h.
Constructor & Destructor Documentation
FourXFour_Board()
FourXFour_Board::FourXFour_Board ()
Definition at line 486 of file XO_Classes.cpp.
                                 : Board(4, 4) {
    for (auto& row : board)
        for (auto& cell : row)
            cell = blank_symbol;
    initializeStartingPositions();
}
References blank_symbol, Board< char >::Board(), Board< char >::board, and initializeStartingPositions().
Member Function Documentation
game_is_over()
bool FourXFour_Board::game_is_over (Player< char > *) virtual
Check if the game is over.
Implements Board< char >.
Definition at line 615 of file XO_Classes.cpp.
{
    return is_win(player) || is_draw(player);
}
References is_draw(), and is_win().
get_player_pieces()
vector< pair< int, int > > FourXFour_Board::get_player_pieces (char symbol)
Definition at line 619 of file XO_Classes.cpp.
{
    vector<pair<int, int>> pieces;
    for (int i = 0; i < rows; i++) {
        for (int j = 0; j < columns; j++) {
            if (board[i][j] == symbol) {
                pieces.push_back({ i, j });
            }
        }
    }
    return pieces;
}
References Board< char >::board, Board< char >::columns, and Board< char >::rows.
Referenced by FourXFour_UI::get_move().
has_three_in_row()
bool FourXFour_Board::has_three_in_row (char symbol)
Definition at line 573 of file XO_Classes.cpp.
{
    for (int i = 0; i < rows; i++) {
        for (int j = 0; j <= columns - 3; j++) {
            if (board[i][j] == symbol && board[i][j + 1] == symbol && board[i][j + 2] == symbol)
                return true;
        }
    }
    for (int j = 0; j < columns; j++) {
        for (int i = 0; i <= rows - 3; i++) {
            if (board[i][j] == symbol && board[i + 1][j] == symbol && board[i + 2][j] == symbol)
                return true;
        }
    }
    for (int i = 0; i <= rows - 3; i++) {
        for (int j = 0; j <= columns - 3; j++) {
            if (board[i][j] == symbol && board[i + 1][j + 1] == symbol && board[i + 2][j + 2] == symbol)
                return true;
        }
    }
    for (int i = 0; i <= rows - 3; i++) {
        for (int j = 2; j < columns; j++) {
            if (board[i][j] == symbol && board[i + 1][j - 1] == symbol && board[i + 2][j - 2] == symbol)
                return true;
        }
    }
    return false;
}
References Board< char >::board, Board< char >::columns, and Board< char >::rows.
Referenced by is_win().
initializeStartingPositions()
void FourXFour_Board::initializeStartingPositions () private
Definition at line 494 of file XO_Classes.cpp.
{
    board[0][0] = 'X'; board[0][1] = 'O'; board[0][2] = 'X'; board[0][3] = 'O';
    board[3][0] = 'O'; board[3][1] = 'X'; board[3][2] = 'O'; board[3][3] = 'X';
    playerX_pieces = { {0,0}, {0,2}, {3,1}, {3,3} };
    playerO_pieces = { {0,1}, {0,3}, {3,0}, {3,2} };
}
References Board< char >::board, playerO_pieces, and playerX_pieces.
Referenced by FourXFour_Board().
is_draw()
bool FourXFour_Board::is_draw (Player< char > *) virtual
Check if the game ended in a draw.
Implements Board< char >.
Definition at line 610 of file XO_Classes.cpp.
{
    return n_moves > 50;
}
References Board< char >::n_moves.
Referenced by game_is_over().
is_lose()
bool FourXFour_Board::is_lose (Player< char > *) inline virtual
Check if a player has lost.
Implements Board< char >.
Definition at line 101 of file XO_Classes.h.
{ return false; }
is_win()
bool FourXFour_Board::is_win (Player< char > *) virtual
Check if a player has won.
Implements Board< char >.
Definition at line 606 of file XO_Classes.cpp.
{
    return has_three_in_row(player->get_symbol());
}
References Player< T >::get_symbol(), and has_three_in_row().
Referenced by game_is_over().
isAdjacent()
bool FourXFour_Board::isAdjacent (int from_x, int from_y, int to_x, int to_y) private
Definition at line 502 of file XO_Classes.cpp.
{
    int dx = abs(from_x - to_x);
    int dy = abs(from_y - to_y);
    return (dx == 1 && dy == 0) || (dx == 0 && dy == 1);
}
Referenced by isValidMove().
isValidMove()
bool FourXFour_Board::isValidMove (int from_x, int from_y, int to_x, int to_y, char symbol) private
Definition at line 509 of file XO_Classes.cpp.
{
    if (from_x < 0 || from_x >= rows || from_y < 0 || from_y >= columns ||
        to_x < 0 || to_x >= rows || to_y < 0 || to_y >= columns) {
        return false;
    }
    if (board[from_x][from_y] != symbol) {
        return false;
    }
    if (board[to_x][to_y] != blank_symbol) {
        return false;
    }
    if (!isAdjacent(from_x, from_y, to_x, to_y)) {
        return false;
    }
    return true;
}
References blank_symbol, Board< char >::board, Board< char >::columns, isAdjacent(), and Board< char >::rows.
Referenced by update_board().
update_board()
bool FourXFour_Board::update_board (Move< char > * move) virtual
Update the board with a new move.
Parameters
move The move object containing position and symbol.
Returns
true if the move is valid and applied, false otherwise.
Implements Board< char >.
Definition at line 531 of file XO_Classes.cpp.
{
    int combined_x = move->get_x();
    int combined_y = move->get_y();
    char symbol = move->get_symbol();
    int from_x = combined_x / 10;
    int to_x = combined_x % 10;
    int from_y = combined_y / 10;
    int to_y = combined_y % 10;
    if (!isValidMove(from_x, from_y, to_x, to_y, symbol)) {
        return false;
    }
    board[from_x][from_y] = blank_symbol;
    board[to_x][to_y] = symbol;
    n_moves++;
    if (symbol == 'X') {
        for (auto& piece : playerX_pieces) {
            if (piece.first == from_x && piece.second == from_y) {
                piece.first = to_x;
                piece.second = to_y;
                break;
            }
        }
    }
    else {
        for (auto& piece : playerO_pieces) {
            if (piece.first == from_x && piece.second == from_y) {
                piece.first = to_x;
                piece.second = to_y;
                break;
            }
        }
    }
    return true;
}
References blank_symbol, Board< char >::board, Move< T >::get_symbol(), Move< T >::get_x(), Move< T >::get_y(), isValidMove(), Board< char >::n_moves, playerO_pieces, and playerX_pieces.
Member Data Documentation
blank_symbol
char FourXFour_Board::blank_symbol = '.' private
Definition at line 89 of file XO_Classes.h.
Referenced by FourXFour_Board(), isValidMove(), and update_board().
playerO_pieces
vector<pair<int, int> > FourXFour_Board::playerO_pieces private
Definition at line 91 of file XO_Classes.h.
Referenced by initializeStartingPositions(), and update_board().
playerX_pieces
vector<pair<int, int> > FourXFour_Board::playerX_pieces private
Definition at line 90 of file XO_Classes.h.
Referenced by initializeStartingPositions(), and update_board().
The documentation for this class was generated from the following files:
XO/XO_Classes.h
XO/XO_Classes.cpp