Board Games Collection: ConnectFour_Board Class Reference
ConnectFour_Board Class Reference
#include <XO_Classes.h>
Public Member Functions
ConnectFour_Board ()
bool update_board (Move< char > *move)
Update the board with a new move.
bool is_win (Player< char > *player)
Check if a player has won.
bool is_lose (Player< char > *player)
Check if a player has lost.
bool is_draw (Player< char > *player)
Check if the game ended in a draw.
bool game_is_over (Player< char > *player)
Check if the game is over.
bool is_column_full (int col)
int get_lowest_empty_row (int col)
bool check_four_in_line (char symbol)
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Attributes
char blank_symbol = '.'
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Definition at line 109 of file XO_Classes.h.
Constructor & Destructor Documentation
ConnectFour_Board()
ConnectFour_Board::ConnectFour_Board ()
Definition at line 742 of file XO_Classes.cpp.
                                     : Board(6, 7) {
    for (auto& row : board)
        for (auto& cell : row)
            cell = blank_symbol;
}
References blank_symbol, Board< char >::Board(), and Board< char >::board.
Member Function Documentation
check_four_in_line()
bool ConnectFour_Board::check_four_in_line (char symbol)
Definition at line 779 of file XO_Classes.cpp.
{
    for (int row = 0; row < rows; row++) {
        for (int col = 0; col <= columns - 4; col++) {
            if (board[row][col] == symbol && board[row][col + 1] == symbol &&
                board[row][col + 2] == symbol && board[row][col + 3] == symbol) {
                return true;
            }
        }
    }
    for (int row = 0; row <= rows - 4; row++) {
        for (int col = 0; col < columns; col++) {
            if (board[row][col] == symbol &&board[row + 1][col] == symbol &&
                board[row + 2][col] == symbol && board[row + 3][col] == symbol) {
                return true;
            }
        }
    }
    for (int row = 0; row <= rows - 4; row++) {
        for (int col = 0; col <= columns - 4; col++) {
            if (board[row][col] == symbol &&board[row + 1][col + 1] == symbol &&
                board[row + 2][col + 2] == symbol &&board[row + 3][col + 3] == symbol) {
                return true;
            }
        }
    }
    for (int row = 0; row <= rows - 4; ++row) {
        for (int col = 3; col < columns; ++col) {
            if (board[row][col] == symbol &&board[row + 1][col - 1] == symbol &&
                board[row + 2][col - 2] == symbol &&board[row + 3][col - 3] == symbol) {
                return true;
            }
        }
    }
    return false;
}
References Board< char >::board, Board< char >::columns, and Board< char >::rows.
Referenced by is_win().
game_is_over()
bool ConnectFour_Board::game_is_over (Player< char > *) virtual
Check if the game is over.
Implements Board< char >.
Definition at line 828 of file XO_Classes.cpp.
{
    return is_win(player) || is_draw(player);
}
References is_draw(), and is_win().
get_lowest_empty_row()
int ConnectFour_Board::get_lowest_empty_row (int col)
Definition at line 770 of file XO_Classes.cpp.
{
    for (int row = rows - 1; row >= 0; row--) {
        if (board[row][col] == blank_symbol) {
            return row;
        }
    }
    return -1;
}
References blank_symbol, Board< char >::board, and Board< char >::rows.
Referenced by ConnectFour_UI::get_move(), and update_board().
is_column_full()
bool ConnectFour_Board::is_column_full (int col)
Definition at line 766 of file XO_Classes.cpp.
{
    return board[0][col] != blank_symbol;
}
References blank_symbol, and Board< char >::board.
Referenced by ConnectFour_UI::get_move(), is_draw(), and update_board().
is_draw()
bool ConnectFour_Board::is_draw (Player< char > *) virtual
Check if the game ended in a draw.
Implements Board< char >.
Definition at line 819 of file XO_Classes.cpp.
{
    for (int col = 0; col < columns; col++) {
        if (!is_column_full(col)) {
            return false;
        }
    }
    return !is_win(player);
}
References Board< char >::columns, is_column_full(), and is_win().
Referenced by game_is_over().
is_lose()
bool ConnectFour_Board::is_lose (Player< char > *) inline virtual
Check if a player has lost.
Implements Board< char >.
Definition at line 117 of file XO_Classes.h.
{ return false; }
is_win()
bool ConnectFour_Board::is_win (Player< char > *) virtual
Check if a player has won.
Implements Board< char >.
Definition at line 815 of file XO_Classes.cpp.
{
    return check_four_in_line(player->get_symbol());
}
References check_four_in_line(), and Player< T >::get_symbol().
Referenced by game_is_over(), and is_draw().
update_board()
bool ConnectFour_Board::update_board (Move< char > * move) virtual
Update the board with a new move.
Parameters
move The move object containing position and symbol.
Returns
true if the move is valid and applied, false otherwise.
Implements Board< char >.
Definition at line 748 of file XO_Classes.cpp.
{
    int column = move->get_y();
    char symbol = move->get_symbol();
    if (column < 0 || column >= columns || is_column_full(column)) {
        return false;
    }
    int row = get_lowest_empty_row(column);
    if (row == -1) {
        return false;
    }
    n_moves++;
    board[row][column] = toupper(symbol);
    return true;
}
References Board< char >::board, Board< char >::columns, get_lowest_empty_row(), Move< T >::get_symbol(), Move< T >::get_y(), is_column_full(), and Board< char >::n_moves.
Member Data Documentation
blank_symbol
char ConnectFour_Board::blank_symbol = '.' private
Definition at line 111 of file XO_Classes.h.
Referenced by ConnectFour_Board(), get_lowest_empty_row(), and is_column_full().
The documentation for this class was generated from the following files:
XO/XO_Classes.h
XO/XO_Classes.cpp