Board Games Collection: Move< T > Class Template Reference
Move< T > Class Template Reference
Represents a single move in a board game.
#include <BoardGame_Classes.h>
Public Member Functions
Move (int x, int y, T symbol)
Construct a move at (x, y) using a symbol.
int get_x () const
Get row index.
int get_y () const
Get column index.
T get_symbol () const
Get the move symbol.
Private Attributes
int x
Row index.
int y
Column index.
T symbol
Symbol used in the move.
Detailed Description
template<typename T>
class Move< T >
Represents a single move in a board game.
Template Parameters
T Type of symbol placed on the board (e.g., char, int).
Definition at line 113 of file BoardGame_Classes.h.
Constructor & Destructor Documentation
Move()
template<typename T> Move< T >::Move (int x, int y, T symbol) inline
Construct a move at (x, y) using a symbol.
Definition at line 120 of file BoardGame_Classes.h.
: x(x), y(y), symbol(symbol) {}
References symbol, x, and y.
Member Function Documentation
get_symbol()
template<typename T> T Move< T >::get_symbol () const inline
Get the move symbol.
Definition at line 129 of file BoardGame_Classes.h.
{ return symbol; }
References symbol.
Referenced by ConnectFour_Board::update_board(), DiamondXO_Board::update_board(), FiveXFive_Board::update_board(), FourXFour_Board::update_board(), InfinityXO_Board::update_board(), MathXO_Board::update_board(), ObstacleXO_Board::update_board(), PyramidXO_Board::update_board(), ReverseXO_Board::update_board(), SUS_Board::update_board(), and WordXO_Board::update_board().
get_x()
template<typename T> int Move< T >::get_x () const inline
Get row index.
Definition at line 123 of file BoardGame_Classes.h.
{ return x; }
References x.
Referenced by DiamondXO_Board::update_board(), FiveXFive_Board::update_board(), FourXFour_Board::update_board(), InfinityXO_Board::update_board(), MathXO_Board::update_board(), ObstacleXO_Board::update_board(), PyramidXO_Board::update_board(), ReverseXO_Board::update_board(), SUS_Board::update_board(), and WordXO_Board::update_board().
get_y()
template<typename T> int Move< T >::get_y () const inline
Get column index.
Definition at line 126 of file BoardGame_Classes.h.
{ return y; }
References y.
Referenced by ConnectFour_Board::update_board(), DiamondXO_Board::update_board(), FiveXFive_Board::update_board(), FourXFour_Board::update_board(), InfinityXO_Board::update_board(), MathXO_Board::update_board(), ObstacleXO_Board::update_board(), PyramidXO_Board::update_board(), ReverseXO_Board::update_board(), SUS_Board::update_board(), and WordXO_Board::update_board().
Member Data Documentation
symbol
template<typename T> T Move< T >::symbol private
Symbol used in the move.
Definition at line 116 of file BoardGame_Classes.h.
Referenced by get_symbol(), and Move().
x
template<typename T> int Move< T >::x private
Row index.
Definition at line 114 of file BoardGame_Classes.h.
Referenced by get_x(), and Move().
y
template<typename T> int Move< T >::y private
Column index.
Definition at line 115 of file BoardGame_Classes.h.
Referenced by get_y(), and Move().
The documentation for this class was generated from the following file:
XO/BoardGame_Classes.h