Board Games Collection: WordXO_Board Class Reference
WordXO_Board Class Reference
#include <XO_Classes.h>
Public Member Functions
WordXO_Board ()
bool update_board (Move< char > *move)
Update the board with a new move.
bool is_win (Player< char > *player)
Check if a player has won.
bool is_lose (Player< char > *player)
Check if a player has lost.
bool is_draw (Player< char > *player)
Check if the game ended in a draw.
bool game_is_over (Player< char > *player)
Check if the game is over.
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Member Functions
void load_dictionary (const string &filename)
bool is_valid_word (const string &word) const
string get_cells_as_string (int x1, int y1, int x2, int y2, int x3, int y3) const
Private Attributes
char blank_symbol = '.'
unordered_set< string > dictionary
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Definition at line 155 of file XO_Classes.h.
Constructor & Destructor Documentation
WordXO_Board()
WordXO_Board::WordXO_Board ()
Definition at line 1144 of file XO_Classes.cpp.
                           : Board(3, 3) {
    for (auto& row : board)
        for (auto& cell : row)
            cell = blank_symbol;
    load_dictionary("dic.txt");
}
References blank_symbol, Board< char >::Board(), Board< char >::board, and load_dictionary().
Member Function Documentation
game_is_over()
bool WordXO_Board::game_is_over (Player< char > *) virtual
Check if the game is over.
Implements Board< char >.
Definition at line 1229 of file XO_Classes.cpp.
{
    return is_win(player) || is_draw(player);
}
References is_draw(), and is_win().
get_cells_as_string()
string WordXO_Board::get_cells_as_string (int x1, int y1, int x2, int y2, int x3, int y3) const private
Definition at line 1170 of file XO_Classes.cpp.
{
    string result;
    result += board[x1][y1];
    result += board[x2][y2];
    result += board[x3][y3];
    return result;
}
References Board< char >::board.
Referenced by is_win().
is_draw()
bool WordXO_Board::is_draw (Player< char > *) virtual
Check if the game ended in a draw.
Implements Board< char >.
Definition at line 1222 of file XO_Classes.cpp.
{
    if (n_moves == 9 && !is_win(player)) {
        return true;
    }
    return false;
}
References is_win(), and Board< char >::n_moves.
Referenced by game_is_over().
is_lose()
bool WordXO_Board::is_lose (Player< char > *) inline virtual
Check if a player has lost.
Implements Board< char >.
Definition at line 168 of file XO_Classes.h.
{ return false; }
is_valid_word()
bool WordXO_Board::is_valid_word (const string & word) const private
Definition at line 1166 of file XO_Classes.cpp.
{
    return dictionary.find(word) != dictionary.end();
}
References dictionary.
Referenced by is_win().
is_win()
bool WordXO_Board::is_win (Player< char > *) virtual
Check if a player has won.
Implements Board< char >.
Definition at line 1192 of file XO_Classes.cpp.
{
    char symbol = player->get_symbol();
    for (int i = 0; i < 3; ++i) {
        if (board[i][0] != blank_symbol && board[i][1] != blank_symbol && board[i][2] != blank_symbol) {
            string word = get_cells_as_string(i, 0, i, 1, i, 2);
            if (is_valid_word(word)) return true;
        }
    }
    for (int j = 0; j < 3; ++j) {
        if (board[0][j] != blank_symbol && board[1][j] != blank_symbol && board[2][j] != blank_symbol) {
            string word = get_cells_as_string(0, j, 1, j, 2, j);
            if (is_valid_word(word)) return true;
        }
    }
    if (board[0][0] != blank_symbol && board[1][1] != blank_symbol && board[2][2] != blank_symbol) {
        string word = get_cells_as_string(0, 0, 1, 1, 2, 2);
        if (is_valid_word(word)) return true;
    }
    if (board[0][2] != blank_symbol && board[1][1] != blank_symbol && board[2][0] != blank_symbol) {
        string word = get_cells_as_string(0, 2, 1, 1, 2, 0);
        if (is_valid_word(word)) return true;
    }
    return false;
}
References blank_symbol, Board< char >::board, get_cells_as_string(), Player< T >::get_symbol(), and is_valid_word().
Referenced by game_is_over(), and is_draw().
load_dictionary()
void WordXO_Board::load_dictionary (const string & filename) private
Definition at line 1151 of file XO_Classes.cpp.
{
    ifstream file(filename);
    if (!file) {
        cerr << "Error: Could not open dictionary file " << filename << endl;
        return;
    }
    string word;
    while (file >> word) {
        if (word.length() == 3) {
            dictionary.insert(word);
        }
    }
    file.close();
}
References dictionary.
Referenced by WordXO_Board().
update_board()
bool WordXO_Board::update_board (Move< char > * move) virtual
Update the board with a new move.
Parameters
move The move object containing position and symbol.
Returns
true if the move is valid and applied, false otherwise.
Implements Board< char >.
Definition at line 1178 of file XO_Classes.cpp.
{
    int x = move->get_x();
    int y = move->get_y();
    char symbol = move->get_symbol();
    if (x < 0 || x >= rows || y < 0 || y >= columns || board[x][y] != blank_symbol) {
        return false;
    }
    n_moves++;
    board[x][y] = toupper(symbol);
    return true;
}
References blank_symbol, Board< char >::board, Board< char >::columns, Move< T >::get_symbol(), Move< T >::get_x(), Move< T >::get_y(), Board< char >::n_moves, and Board< char >::rows.
Member Data Documentation
blank_symbol
char WordXO_Board::blank_symbol = '.' private
Definition at line 157 of file XO_Classes.h.
Referenced by is_win(), update_board(), and WordXO_Board().
dictionary
unordered_set<string> WordXO_Board::dictionary private
Definition at line 158 of file XO_Classes.h.
Referenced by is_valid_word(), and load_dictionary().
The documentation for this class was generated from the following files:
XO/XO_Classes.h
XO/XO_Classes.cpp